@extends('layouts.app')
@section('title','Applicator Registration')
@section('content')
<div class="form-shell"><div class="page-head"><div><p class="eyebrow">Applicator onboarding</p><h1>Request Scratchgard access</h1><p class="muted">PIN is mandatory. It must resolve to an active Scratchgard zone before registration can continue.</p></div></div>
<form method="post" action="{{ route('applicator.register.store') }}" enctype="multipart/form-data" class="card">@csrf
<div class="section-title"><span>01</span><div><h2>Identity</h2><p>Current contact policy: <strong>{{ str_replace('_',' ',strtoupper($identityMode)) }}</strong></p></div></div>
<div class="grid">
<div class="col-6 field"><label>Full legal name *</label><input id="legalName" name="name" value="{{ old('name') }}" required></div>
<div class="col-6 field"><label>Username</label><input id="username" name="username" value="{{ old('username') }}" maxlength="30" autocomplete="username"><small id="usernameStatus" class="muted">Leave blank for an automatic unique username based on your name.</small></div>
@if(in_array($identityMode,['email_only','both','email_or_mobile']))<div class="col-6 field"><label>Email @if(in_array($identityMode,['email_only','both']))*@endif</label><input type="email" name="email" value="{{ old('email') }}" autocomplete="email" @required(in_array($identityMode,['email_only','both']))><small class="muted">Email is stored in normalized lowercase form.</small></div>@endif
@if(in_array($identityMode,['mobile_only','both','email_or_mobile']))
<div class="col-2 field"><label>Country code</label><input name="mobile_country_code" value="{{ old('mobile_country_code',$defaultCountryCode) }}" inputmode="tel" maxlength="5" placeholder="+91"></div>
<div class="col-4 field"><label>Mobile @if(in_array($identityMode,['mobile_only','both']))*@endif</label><input name="mobile" value="{{ old('mobile') }}" inputmode="numeric" maxlength="10" pattern="[0-9]{10}" placeholder="10 digits" @required(in_array($identityMode,['mobile_only','both']))><small class="muted">Exactly 10 digits after country code.</small></div>
@endif
<div class="col-6 field"><label>Password *</label><input type="password" name="password" minlength="10" required autocomplete="new-password"></div><div class="col-6 field"><label>Confirm password *</label><input type="password" name="password_confirmation" minlength="10" required autocomplete="new-password"></div>
</div>
<div class="section-title"><span>02</span><div><h2>Location & zone</h2><p>Zones are resolved from exact PIN memberships in Scratchgard's postal database, not typed state-name matching.</p></div></div>
<div class="grid"><div class="col-4 field"><label>PIN code *</label><input id="regPin" name="pincode" maxlength="6" inputmode="numeric" value="{{ old('pincode') }}" required><small id="pinStatus" class="muted">Enter 6 digits to resolve zone.</small></div><div class="col-8 field"><label>Full address *</label><textarea name="address" required>{{ old('address') }}</textarea></div></div><div id="zoneResult" class="zone-result"></div>
@if($zoneMode==='show_single')<div class="field"><label>Choose your zone</label><select name="zone_id" id="zoneSingle" required><option value="">Resolve PIN first</option></select></div>@elseif($zoneMode==='show_multi' && $allowMulti)<div class="field"><label>Choose zone(s)</label><div id="zoneMulti" class="choice-grid"></div></div>@elseif($zoneMode==='show_multi')<div class="field"><label>Choose your primary zone</label><select name="zone_id" id="zoneSingle" required><option value="">Resolve PIN first</option></select><small class="muted">Multi-zone registration is disabled by default. Super Admin can grant it later to an individual user.</small></div>@endif
<div class="section-title"><span>03</span><div><h2>KYC</h2><p>KYC approval is separate from contact verification.</p></div></div>
<div class="grid"><div class="col-4 field"><label>Document type *</label><select name="document_type" required><option value="Aadhaar">Aadhaar</option><option value="Driving Licence">Driving Licence</option><option value="PAN">PAN</option><option value="Other">Other</option></select></div><div class="col-4 field"><label>Document number *</label><input name="document_number" required></div><div class="col-4 field"><label>Name on document</label><input name="document_name"></div><div class="col-4 field"><label>Document front</label><input type="file" name="document_front" accept="image/*"></div><div class="col-4 field"><label>Document back</label><input type="file" name="document_back" accept="image/*"></div><div class="col-4 field"><label>Address proof</label><input type="file" name="address_proof" accept="image/*"></div><div class="col-4 field"><label>Selfie / live profile photo</label><input type="file" name="selfie" accept="image/*" capture="user"></div><div class="col-4 field"><label>Profile picture</label><input type="file" name="profile_photo" accept="image/*" capture="user"></div></div>
<button class="btn wide">Create registration & verify contact</button></form></div>
@endsection
@push('scripts')<script>
const pin=document.getElementById('regPin'),result=document.getElementById('zoneResult'),single=document.getElementById('zoneSingle'),multi=document.getElementById('zoneMulti'),statusEl=document.getElementById('pinStatus');let timer;
async function resolvePin(){if(pin.value.length!==6)return;statusEl.textContent='Checking service zone…';const u=new URL('{{ route('applicator.register.zone') }}',location.origin);u.searchParams.set('pincode',pin.value);const d=await fetch(u).then(r=>r.json());if(!d.matches?.length){result.innerHTML='<div class="alert error">No Scratchgard zone exists for this PIN. Registration cannot continue.</div>';statusEl.textContent='No zone found';if(single)single.innerHTML='<option value="">No zone</option>';if(multi)multi.innerHTML='';return;}const loc=d.postal?`${d.postal.city||''} ${d.postal.district||''}, ${d.postal.state||''}`:'';result.innerHTML=`<div class="alert goodish"><strong>${d.matches.length} zone match${d.matches.length>1?'es':''}</strong> for ${loc}<div class="match-list">${d.matches.map(z=>`<span class="pill">${z.code} · ${z.name} <small>${z.match_level}</small></span>`).join('')}</div></div>`;statusEl.textContent='Zone resolved';if(single)single.innerHTML='<option value="">Select zone</option>'+d.matches.map(z=>`<option value="${z.zone_id}">${z.code} — ${z.name}</option>`).join('');if(multi)multi.innerHTML=d.matches.map((z,i)=>`<label class="choice"><input type="checkbox" name="zone_ids[]" value="${z.zone_id}" ${i===0?'checked':''}><span><b>${z.code}</b><small>${z.name}</small></span></label>`).join('')}
pin.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(resolvePin,350)});if(pin.value.length===6)resolvePin();

const nameInput=document.getElementById('legalName'),usernameInput=document.getElementById('username'),usernameStatus=document.getElementById('usernameStatus');let userTimer,userEdited=!!usernameInput.value;
function slugName(v){return v.toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s._-]/g,'').trim().replace(/[\s_-]+/g,'.').replace(/\.+/g,'.').slice(0,30)}
usernameInput.addEventListener('input',()=>{userEdited=true;clearTimeout(userTimer);userTimer=setTimeout(checkUsername,300)});
nameInput.addEventListener('input',()=>{if(!userEdited){usernameInput.value=slugName(nameInput.value);clearTimeout(userTimer);userTimer=setTimeout(checkUsername,300)}});
async function checkUsername(){const v=usernameInput.value.trim();if(!v){usernameStatus.textContent='Leave blank for an automatic unique username based on your name.';return;}const u=new URL('{{ route('applicator.register.username') }}',location.origin);u.searchParams.set('username',v);const d=await fetch(u).then(r=>r.json());if(d.normalized&&d.normalized!==usernameInput.value)usernameInput.value=d.normalized;usernameStatus.textContent=d.message;usernameStatus.className=d.available?'good-text':'text-danger'}
if(usernameInput.value)checkUsername();
</script>@endpush
