<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/app.css"><title>Scratchgard Installer</title></head>
<body><main class="container" style="max-width:900px">
<div class="card"><h1>Scratchgard cPanel Setup Wizard</h1><p class="muted">Use the database credentials created in cPanel → MySQL® Database Wizard. phpMyAdmin is for viewing/managing that database; the application connects using the credentials below.</p></div>
<div class="card"><h2>Server preflight</h2><div class="grid">@foreach($checks as $name=>$ok)<div class="col-6"><span class="badge">{{ $ok?'✓':'✕' }}</span> {{ $name }}</div>@endforeach</div></div>
@if($errors->any())<div class="alert error"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ route('install.run') }}">@csrf
<div class="card"><h2>1. Application</h2><div class="grid"><div class="col-6 field"><label>Application name</label><input name="app_name" value="{{ old('app_name','Scratchgard PPF Operations') }}" required></div><div class="col-6 field"><label>Application URL</label><input name="app_url" value="{{ old('app_url',request()->getSchemeAndHttpHost()) }}" required></div></div></div>
<div class="card"><h2>2. Database</h2><p class="muted">MySQL/MariaDB is recommended for normal cPanel and works with phpMyAdmin. PostgreSQL is supported when your hosting account provides it.</p>
<div class="grid"><div class="col-4 field"><label>Driver</label><select name="db_connection"><option value="mysql">MySQL / MariaDB</option><option value="pgsql">PostgreSQL</option></select></div>
<div class="col-4 field"><label>Host</label><input name="db_host" value="{{ old('db_host','127.0.0.1') }}"></div><div class="col-4 field"><label>Port</label><input name="db_port" value="{{ old('db_port','3306') }}"></div>
<div class="col-6 field"><label>Database name</label><input name="db_database" value="{{ old('db_database') }}" required></div><div class="col-6 field"><label>Database username</label><input name="db_username" value="{{ old('db_username') }}" required></div><div class="col-12 field"><label>Database password</label><input type="password" name="db_password"></div></div></div>
<div class="card"><h2>3. Evidence storage</h2><div class="field"><label>Storage</label><select name="evidence_disk" id="disk"><option value="local">cPanel local/private storage</option><option value="s3">AWS S3</option></select></div>
<div id="s3" style="display:none"><div class="grid"><div class="col-6 field"><label>AWS Access Key ID</label><input name="aws_access_key_id"></div><div class="col-6 field"><label>AWS Secret Access Key</label><input type="password" name="aws_secret_access_key"></div><div class="col-6 field"><label>Region</label><input name="aws_default_region" value="ap-south-1"></div><div class="col-6 field"><label>Bucket</label><input name="aws_bucket"></div></div></div></div>
<div class="card"><h2>4. First Super Admin</h2><div class="grid"><div class="col-6 field"><label>Name</label><input name="admin_name" value="{{ old('admin_name') }}" required></div><div class="col-6 field"><label>Email</label><input type="email" name="admin_email" value="{{ old('admin_email') }}" required></div><div class="col-6 field"><label>Mobile</label><input name="admin_mobile" value="{{ old('admin_mobile') }}"></div><div class="col-6"></div><div class="col-6 field"><label>Password</label><input type="password" name="admin_password" required></div><div class="col-6 field"><label>Confirm password</label><input type="password" name="admin_password_confirmation" required></div></div></div>
<button class="btn good" type="submit">Test connections & Install Scratchgard</button>
</form></main>
<script>const d=document.getElementById('disk'),s=document.getElementById('s3');function x(){s.style.display=d.value==='s3'?'block':'none'}d.addEventListener('change',x);x();</script>
</body></html>
