@extends('layouts.app')
@section('title','Edit '.$user->name)
@section('content')
<div class="page-head"><div><p class="eyebrow">User #{{ $user->id }}</p><h1>{{ $user->name }}</h1><p class="muted">Admin can update profile, identity verification flags, zone scope and individual permission overrides.</p></div></div>
<form method="post" action="{{ route('users.update',$user) }}">@csrf @method('PUT')
<div class="card"><h2>Profile & operational scope</h2><div class="grid"><div class="col-4 field"><label>Role</label><select name="role_id" id="editRole">@foreach($roles as $r)<option value="{{ $r->id }}" @selected($user->role_id===$r->id)>{{ $r->name }}</option>@endforeach</select></div><div class="col-4 field"><label>Name</label><input name="name" value="{{ old('name',$user->name) }}" required></div><div class="col-4 field"><label>Employee reference</label><input name="employee_reference" value="{{ old('employee_reference',$user->employee_reference) }}"></div><div class="col-4 field"><label>Username</label><input name="username" value="{{ old('username',$user->username) }}" required></div><div class="col-4 field"><label>Email</label><input type="email" name="email" value="{{ old('email',$user->email) }}"></div><div class="col-2 field"><label>Country code</label><input name="mobile_country_code" value="{{ old('mobile_country_code',$user->mobile_country_code ?: $defaultCountryCode) }}" maxlength="5"></div><div class="col-2 field"><label>Mobile</label><input name="mobile" value="{{ old('mobile',$user->mobile_national_number) }}" maxlength="10" pattern="[0-9]{10}" inputmode="numeric"></div><div class="col-4 field verifier-field" @if($user->role?->slug!=='external_verifier') hidden @endif><label>Showroom *</label><select name="showroom_id"><option value="">Select showroom</option>@foreach($showrooms as $s)<option value="{{ $s->id }}" @selected($user->showroom_id===$s->id)>{{ $s->vendor?->name }} — {{ $s->name }} ({{ $s->pincode }})</option>@endforeach</select></div><div class="col-4 field verifier-field" @if($user->role?->slug!=='external_verifier') hidden @endif><label>Designation</label><input name="designation" value="{{ old('designation',$user->designation) }}"></div><div class="col-4 verifier-field" @if($user->role?->slug!=='external_verifier') hidden @endif><label class="check"><input type="checkbox" name="approval_otp_required" value="1" @checked($user->approval_otp_required)> Require email OTP for work review</label></div><div class="col-4 field"><label>PIN</label><input name="pincode" maxlength="6" value="{{ old('pincode',$user->pincode) }}"></div><div class="col-12 field"><label>Address</label><textarea name="address">{{ old('address',$user->address) }}</textarea></div>
<div class="col-6 field"><label>Zones</label><select name="zones[]" multiple size="7">@foreach($zones as $z)<option value="{{ $z->id }}" @selected($user->zones->contains('id',$z->id))>{{ $z->code }} — {{ $z->name }}</option>@endforeach</select></div><div class="col-3 field"><label>Primary zone</label><select name="primary_zone_id"><option value="">Select</option>@foreach($zones as $z)<option value="{{ $z->id }}" @selected($user->primary_zone_id===$z->id)>{{ $z->code }}</option>@endforeach</select></div><div class="col-3 field"><label>Status</label><select name="status">@foreach(['verification_pending','pending','active','suspended','disabled'] as $st)<option @selected($user->status===$st)>{{ $st }}</option>@endforeach</select></div><div class="col-4"><label class="check"><input type="checkbox" name="allow_multiple_zones" value="1" @checked($user->allow_multiple_zones)> Multi-zone exception</label></div><div class="col-4"><label class="check"><input type="checkbox" name="allow_zone_self_selection" value="1" @checked($user->allow_zone_self_selection)> Self-select matching zone</label></div><div class="col-2"><label class="check"><input type="checkbox" name="email_verified" value="1" @checked($user->email_verified_at)> Email verified</label></div><div class="col-2"><label class="check"><input type="checkbox" name="mobile_verified" value="1" @checked($user->mobile_verified_at)> Mobile verified</label></div><div class="col-4 field"><label>New password (optional)</label><input type="password" name="password"></div></div></div>
<div class="card"><h2>Per-user permission overrides</h2><p class="muted">Role defaults apply unless explicit Grant/Deny exists. This is how Super Admin can give payment revert, KYC approval, work approval, etc. to only one selected manager.</p><div class="table-wrap"><table><thead><tr><th>Permission</th><th>Role default</th><th>Grant</th><th>Deny</th></tr></thead><tbody>@foreach($permissions as $p)@php($roleDefault=$user->role?->permissions?->contains('id',$p->id) ?? false)<tr><td><strong>{{ $p->name }}</strong><br><span class="muted">{{ $p->slug }}</span></td><td>{{ $roleDefault?'Yes':'No' }}</td><td><input class="check-input" type="checkbox" name="grants[]" value="{{ $p->id }}" @checked(($overrides[$p->id] ?? null)===1)></td><td><input class="check-input" type="checkbox" name="denies[]" value="{{ $p->id }}" @checked(($overrides[$p->id] ?? null)===0)></td></tr>@endforeach</tbody></table></div></div><button class="btn good">Save user</button></form>
@if(auth()->user()->role?->slug==='super_admin')<form method="post" action="{{ route('users.delete',$user) }}" onsubmit="return confirm('Disable this user? Historical records are retained.')">@csrf @method('DELETE')<button class="btn danger">Disable user</button></form>@endif
@endsection

@push('scripts')<script>const editRole=document.getElementById('editRole');function toggleVerifierFields(){const text=editRole?.selectedOptions?.[0]?.textContent?.toLowerCase()||'';document.querySelectorAll('.verifier-field').forEach(el=>el.hidden=!text.includes('external verifier'));}editRole?.addEventListener('change',toggleVerifierFields);toggleVerifierFields();</script>@endpush
