@extends('layouts.app')
@section('title',request('role')==='applicator'?'Applicators':(request('role')==='external_verifier'?'Verifiers':'Users'))
@section('content')
@php
$pr=app(\App\Plugins\PluginRuntime::class);$userCols=$pr->tableColumnsFor('users',['screen'=>'index'],auth()->user());$hasUserActions=$users->getCollection()->contains(fn($u)=>count($pr->tableActionsFor('users',$u,['screen'=>'index'],auth()->user()))>0);
@endphp
<div class="page-head"><div><p class="eyebrow">Identity & access</p><h1>{{ request('role')==='applicator'?'Applicators':(request('role')==='external_verifier'?'External Verifiers':'Users') }}</h1><p class="muted">Default: one primary operational zone. Enable multi-zone only globally or for a specific user.</p></div></div>
<div class="plugin-slot">{!! $pr->renderSlot('users.index.before_create',['users'=>$users],auth()->user()) !!}</div>
<form class="card searchbar" method="get">@if(request('role'))<input type="hidden" name="role" value="{{ request('role') }}">@endif<input name="q" value="{{ request('q') }}" placeholder="Search name, username, email or mobile…"><button class="btn secondary">Search</button>@if(request('q'))<a class="btn ghost" href="{{ route('users.index',request('role')?['role'=>request('role')]:[]) }}">Clear</a>@endif</form>
<div class="card"><h2>Create user</h2><form method="post" action="{{ route('users.store') }}">@csrf<div class="grid">
<div class="col-4 field"><label>Role *</label><select name="role_id" id="createRole" required>@foreach($roles as $r)<option value="{{ $r->id }}">{{ $r->name }}</option>@endforeach</select></div><div class="col-4 field"><label>Name *</label><input name="name" required></div><div class="col-4 field"><label>Employee/internal reference</label><input name="employee_reference"></div>
<div class="col-4 field"><label>Username</label><input name="username" placeholder="Auto from name if blank"><small class="muted">Unique login ID.</small></div><div class="col-4 field"><label>Email</label><input type="email" name="email"><small class="muted">Normalized lowercase.</small></div><div class="col-2 field"><label>Country code</label><input name="mobile_country_code" value="{{ $defaultCountryCode }}" maxlength="5"></div><div class="col-2 field"><label>Mobile</label><input name="mobile" maxlength="10" pattern="[0-9]{10}" inputmode="numeric" placeholder="10 digits"></div><div class="col-4 field"><label>Temporary password *</label><input type="password" name="password" minlength="10" required></div><div class="col-4 field verifier-field" hidden><label>Showroom *</label><select name="showroom_id"><option value="">Select showroom</option>@foreach($showrooms as $s)<option value="{{ $s->id }}">{{ $s->vendor?->name }} — {{ $s->name }} ({{ $s->pincode }})</option>@endforeach</select><small class="muted">Required for third-party showroom manager / external verifier.</small></div><div class="col-4 field verifier-field" hidden><label>Designation</label><input name="designation" placeholder="Showroom Manager / Quality Manager"></div><div class="col-4 verifier-field" hidden><label class="check"><input type="checkbox" name="approval_otp_required" value="1" checked> Require email OTP for every work review decision</label></div>
<div class="col-4 field"><label>PIN code</label><input name="pincode" maxlength="6" inputmode="numeric"><small class="muted">Mandatory for Zonal Manager and Applicator; used to resolve zone.</small></div><div class="col-8 field"><label>Address</label><textarea name="address"></textarea></div>
<div class="col-6 field"><label>Assigned zones</label><select name="zones[]" multiple size="6">@foreach($zones as $z)<option value="{{ $z->id }}">{{ $z->code }} — {{ $z->name }}</option>@endforeach</select><small class="muted">Select one unless multi-zone is explicitly enabled.</small></div><div class="col-3 field"><label>Primary zone</label><select name="primary_zone_id"><option value="">First selected/auto</option>@foreach($zones as $z)<option value="{{ $z->id }}">{{ $z->code }}</option>@endforeach</select></div><div class="col-3 field"><label>Status</label><select name="status"><option>verification_pending</option><option>pending</option><option selected>active</option><option>suspended</option><option>disabled</option></select></div>
<div class="col-4"><label class="check"><input type="checkbox" name="allow_multiple_zones" value="1"> Allow multiple zones for this user</label></div><div class="col-4"><label class="check"><input type="checkbox" name="allow_zone_self_selection" value="1"> Allow this user to choose matching zone</label></div><div class="col-2"><label class="check"><input type="checkbox" name="email_verified" value="1"> Email verified by admin</label></div><div class="col-2"><label class="check"><input type="checkbox" name="mobile_verified" value="1"> Mobile verified by admin</label></div>
@include('plugins.partials.form-fields',['formName'=>'user.create','context'=>['roles'=>$roles,'zones'=>$zones]])
</div><div class="subcard"><h3>Optional initial KYC</h3><div class="grid"><div class="col-6 field"><label>Document type</label><input name="document_type"></div><div class="col-6 field"><label>Document number</label><input name="document_number"></div></div></div><button class="btn good">Create user</button></form></div>
<div class="card"><h2>Existing users</h2><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Primary zone / showroom</th><th>Verification</th><th>Status</th>@foreach($userCols as $c)<th>{{ $c['label'] }}</th>@endforeach<th></th>@if($hasUserActions)<th>Extensions</th>@endif</tr></thead><tbody>@foreach($users as $u)<tr><td><strong>{{ $u->name }}</strong><br><span class="muted">@{{ $u->username }} · {{ $u->email ?: 'no email' }} · {{ $u->mobile ?: 'no mobile' }}</span></td><td>{{ $u->role?->name }}</td><td>@if($u->role?->slug==='external_verifier'){{ $u->showroom?->vendor?->name }}<br><small>{{ $u->showroom?->name ?? 'No showroom' }} · {{ $u->designation }}</small>@else{{ $u->primaryZone?->code ?? '—' }} @if($u->allow_multiple_zones)<br><small>{{ $u->zones->pluck('code')->join(', ') }}</small>@endif @endif</td><td><span class="mini-check {{ $u->email_verified_at?'on':'' }}">E</span> <span class="mini-check {{ $u->mobile_verified_at?'on':'' }}">M</span></td><td><span class="badge">{{ $u->status }}</span></td>@foreach($userCols as $c)<td>{!! $pr->renderTableCell($c,$u,['screen'=>'index'],auth()->user()) !!}</td>@endforeach<td><a class="btn secondary small" href="{{ route('users.edit',$u) }}">Edit</a></td>@if($hasUserActions)<td>@include('plugins.partials.table-actions',['actions'=>$pr->tableActionsFor('users',$u,['screen'=>'index'],auth()->user())])</td>@endif</tr>@endforeach</tbody></table></div>{{ $users->links() }}</div>
<div class="plugin-slot">{!! $pr->renderSlot('users.index.after_table',['users'=>$users],auth()->user()) !!}</div>
@endsection

@push('scripts')<script>const role=document.getElementById('createRole');function verifierFields(){const text=role?.selectedOptions?.[0]?.textContent?.toLowerCase()||'';document.querySelectorAll('.verifier-field').forEach(el=>el.hidden=!text.includes('external verifier'));}role?.addEventListener('change',verifierFields);verifierFields();</script>@endpush
