@extends('layouts.app')
@section('title',$workOrder->work_order_number)
@section('content')
@php
$directions = $workOrder->showroom?->latitude && $workOrder->showroom?->longitude
    ? 'https://www.google.com/maps/dir/?api=1&destination='.$workOrder->showroom->latitude.','.$workOrder->showroom->longitude
    : 'https://www.google.com/maps/dir/?api=1&destination='.urlencode(($workOrder->showroom?->address ?? '').' '.($workOrder->showroom?->pincode ?? ''));
$pluginCtx=['workOrder'=>$workOrder];
$pr=app(\App\Plugins\PluginRuntime::class);
@endphp
<div class="plugin-slot">{!! $pr->renderSlot('work.show.before',$pluginCtx,auth()->user()) !!}</div>
<div class="page-head"><div><p class="eyebrow">Work order</p><h1>{{ $workOrder->work_order_number }}</h1><div class="stack"><span class="badge large">{{ $workOrder->status }}</span>@if($workOrder->relationship_type)<span class="pill">{{ str_replace('_',' ',$workOrder->relationship_type) }}</span>@endif</div></div><div class="page-actions">{!! $pr->renderSlot('work.show.header.actions',$pluginCtx,auth()->user()) !!}@if($workOrder->tracking_enabled && $workOrder->tracking_token)<a class="btn secondary" target="_blank" rel="noopener" href="{{ route('tracking.show',$workOrder->tracking_token) }}">Public tracker ↗</a>@endif<a class="btn secondary" target="_blank" rel="noopener" href="{{ $directions }}">Get directions ↗</a></div></div>

@if(auth()->id()===$workOrder->applicator_id)
<div class="field-hero">
<div><span class="eyebrow">Assigned vehicle</span><h2>{{ $workOrder->vehicle?->make }} {{ $workOrder->vehicle?->model }} {{ $workOrder->vehicle?->variant }}</h2><div class="vin-code">VIN {{ $workOrder->vehicle?->vin }}</div><p>{{ $workOrder->vehicle?->registration_number ?? 'Registration not recorded' }} · {{ $workOrder->vehicle?->color ?? 'Colour —' }}</p></div>
<div class="location-card"><strong>{{ $workOrder->showroom?->vendor?->name }} · {{ $workOrder->showroom?->name }}</strong><p>{{ $workOrder->showroom?->address }}<br>PIN {{ $workOrder->showroom?->pincode }}</p><a class="btn wide" target="_blank" rel="noopener" href="{{ $directions }}">Open showroom directions</a></div>
</div>
@endif
<div class="plugin-slot">{!! $pr->renderSlot('work.show.after_field_hero',$pluginCtx,auth()->user()) !!}</div>

<div class="grid">
<div class="col-8">
<div class="card"><div class="card-head"><div><h2>Vehicle & job</h2><p class="muted">All job identity is anchored to the assigned VIN.</p></div></div><div class="detail-grid"><div><small>VIN</small><strong>{{ $workOrder->vehicle?->vin }}</strong></div><div><small>Registration</small><strong>{{ $workOrder->vehicle?->registration_number ?? '—' }}</strong></div><div><small>Vehicle</small><strong>{{ $workOrder->vehicle?->make }} {{ $workOrder->vehicle?->model }}</strong></div><div><small>Variant / colour</small><strong>{{ $workOrder->vehicle?->variant ?? '—' }} / {{ $workOrder->vehicle?->color ?? '—' }}</strong></div><div><small>Package</small><strong>{{ $workOrder->package_code }}</strong></div><div><small>Zone</small><strong>{{ $workOrder->zone?->code }}</strong></div><div><small>Showroom</small><strong>{{ $workOrder->showroom?->name }}</strong></div><div><small>Fixed payment</small><strong>{{ $workOrder->pricing_amount ? '₹'.number_format($workOrder->pricing_amount,2) : 'Not set' }}</strong></div></div></div>
<div class="plugin-slot">{!! $pr->renderSlot('work.show.after_vehicle',$pluginCtx,auth()->user()) !!}</div>

<div class="plugin-slot">{!! $pr->renderSlot('work.show.before_field_execution',$pluginCtx,auth()->user()) !!}</div>
@if(auth()->id()===$workOrder->applicator_id || auth()->user()->hasPermission('work.override'))
<div class="card field-actions"><div class="card-head"><div><h2>Field execution</h2><p class="muted">GPS is requested only at check-in/check-out and when evidence metadata requires it.</p></div></div>
<div class="action-strip"><form method="post" action="{{ route('checkins.store',$workOrder) }}" onsubmit="return attachLocation(this,event)">@csrf<input type="hidden" name="type" value="START"><input type="hidden" name="latitude"><input type="hidden" name="longitude"><input type="hidden" name="accuracy"><button class="btn secondary">1. Start check-in</button></form><form method="post" action="{{ route('work-orders.start',$workOrder) }}">@csrf<button class="btn">2. Start work</button></form></div>
<form method="post" action="{{ route('evidence.store',$workOrder) }}" enctype="multipart/form-data" onsubmit="return attachLocation(this,event)" class="evidence-capture"><div class="section-label">Capture mandatory evidence</div>@csrf<div class="grid"><div class="col-4 field"><label>Stage</label><select name="stage"><option>BEFORE</option><option>DURING</option><option>AFTER</option><option>REWORK_BEFORE</option><option>REWORK_AFTER</option></select></div><div class="col-4 field"><label>Checklist slot</label><select name="slot_code" required><option value="">Choose slot</option>@if($evidenceTemplate)@foreach($evidenceTemplate->slots->sortBy('sort_order') as $slot)<option value="{{ $slot->slot_code }}" data-stage="{{ $slot->stage }}">{{ $slot->stage }} — {{ $slot->label }}</option>@endforeach@endif</select></div><div class="col-4 field"><label>Vehicle area</label><input name="vehicle_area" placeholder="Door edge / bonnet / bumper"></div><div class="col-12 field"><label>Take photo</label><input class="camera-file-fallback" type="file" name="photo" accept="image/*" capture="environment" required hidden><div class="camera-actions"><button type="button" class="btn secondary" onclick="openEvidenceCamera(this)">Open live camera</button><span class="camera-state muted">No image captured</span></div><div class="camera-box" hidden><video playsinline autoplay muted></video><div class="camera-toolbar"><button type="button" class="btn good" onclick="captureEvidenceCamera(this)">Capture</button><button type="button" class="btn ghost" onclick="closeEvidenceCamera(this)">Close</button></div></div><img class="camera-preview" alt="Captured evidence preview" hidden><small class="muted">Live camera is used where supported. On browsers that cannot provide the live camera API, the system falls back to the browser camera capture control.</small></div></div><input type="hidden" name="latitude"><input type="hidden" name="longitude"><input type="hidden" name="gps_accuracy"><button class="btn">Upload evidence</button></form>
<div class="action-strip"><form method="post" action="{{ route('checkins.store',$workOrder) }}" onsubmit="return attachLocation(this,event)">@csrf<input type="hidden" name="type" value="END"><input type="hidden" name="latitude"><input type="hidden" name="longitude"><input type="hidden" name="accuracy"><button class="btn secondary">3. End check-in</button></form><form method="post" action="{{ route('work-orders.submit',$workOrder) }}">@csrf<button class="btn good">4. Submit completed work</button></form></div></div>
@endif
<div class="plugin-slot">{!! $pr->renderSlot('work.show.after_field_execution',$pluginCtx,auth()->user()) !!}</div>

<div class="plugin-slot">{!! $pr->renderSlot('work.show.before_evidence',$pluginCtx,auth()->user()) !!}</div>
@if($evidenceTemplate)<div class="card"><h2>Mandatory photo checklist</h2><p class="muted">{{ $evidenceTemplate->name }} · v{{ $evidenceTemplate->version }}</p><div class="table-wrap"><table><thead><tr><th>Stage</th><th>Area / photo</th><th>Guidance</th><th>Status</th></tr></thead><tbody>@foreach($evidenceTemplate->slots->sortBy('sort_order') as $slot)@php($done=$workOrder->evidence->first(fn($e)=>$e->stage===$slot->stage && $e->slot_code===$slot->slot_code && !$e->deleted_at))<tr><td>{{ $slot->stage }}</td><td>{{ $slot->label }}<br><span class="muted">{{ $slot->slot_code }}</span></td><td>{{ $slot->closeup_hint }}</td><td><span class="badge {{ $done?'success':'' }}">{{ $done?'✓ Captured':($slot->mandatory?'Required':'Optional') }}</span></td></tr>@endforeach</tbody></table></div></div>@endif

<div class="card"><h2>Evidence</h2><div class="table-wrap"><table><thead><tr><th>Stage</th><th>Slot</th><th>GPS</th><th>Captured</th><th></th></tr></thead><tbody>@forelse($workOrder->evidence as $e)<tr><td>{{ $e->stage }}</td><td>{{ $e->slot_code }}</td><td>{{ $e->latitude && $e->longitude ? $e->latitude.', '.$e->longitude : '—' }}</td><td>{{ optional($e->captured_at)->format('d M Y H:i') }}</td><td><a href="{{ route('evidence.view',$e) }}" target="_blank">View</a></td></tr>@empty<tr><td colspan="5">No evidence yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="plugin-slot">{!! $pr->renderSlot('work.show.after_evidence',$pluginCtx,auth()->user()) !!}</div>
<div class="plugin-slot">{!! $pr->renderSlot('work.show.before_conversation',$pluginCtx,auth()->user()) !!}</div>

<div class="card"><h2>Work conversation</h2><div class="conversation compact">@forelse($messages as $m)<div class="message"><div class="avatar">{{ strtoupper(substr($m->sender_name ?? '?',0,1)) }}</div><div><div class="message-head"><strong>{{ $m->sender_name ?? '#'.$m->sender_id }}</strong><small>{{ \Illuminate\Support\Carbon::parse($m->created_at)->format('d M Y H:i') }}</small></div><p>{{ $m->message }}</p></div></div>@empty<p class="muted">No work messages yet.</p>@endforelse</div><form method="post" action="{{ route('messages.store',$workOrder) }}">@csrf<div class="field"><textarea name="message" placeholder="Operational note or message…" required></textarea></div><button class="btn secondary">Send message</button></form></div>
<div class="plugin-slot">{!! $pr->renderSlot('work.show.after_conversation',$pluginCtx,auth()->user()) !!}</div>
@include('plugins.partials.tabs',['screen'=>'work.show','context'=>$pluginCtx])

@if(auth()->user()->role?->slug==='super_admin' || auth()->user()->hasPermission('complaints.manage'))
<div class="card"><div class="card-head"><div><h2>Complaint / rework</h2><p class="muted">Complaint creates a formal ticket and protects evidence from normal retention deletion.</p></div></div><form method="post" action="{{ route('complaints.store',$workOrder) }}">@csrf<div class="grid"><div class="col-4 field"><label>Severity</label><select name="severity"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></div><div class="col-4 field"><label>Responsibility</label><input name="responsibility_status" value="under_review"></div><div class="col-4 field"><label>Assign rework Applicator (optional)</label><select name="assigned_applicator_id"><option value="">Current / later</option>@foreach($applicators as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div><div class="col-12 field"><label>Description *</label><textarea name="description" required></textarea></div><div class="col-12 field"><label>Affected panels</label><input name="affected_panels" placeholder="bonnet, left door, front bumper"></div></div><button class="btn bad">Open complaint + ticket</button></form>
@if($complaints->count())<div class="case-list">@foreach($complaints as $c)<div class="case-card"><div class="stack between"><div><strong>Complaint #{{ $c->id }}</strong> @if($c->ticket)<a class="pill" href="{{ route('tickets.show',$c->ticket) }}">{{ $c->ticket->ticket_number }}</a>@endif</div><span class="badge">{{ $c->status }}</span></div><p>{{ $c->description }}</p><small class="muted">{{ $c->severity }} · {{ $c->created_at?->format('d M Y H:i') }}</small><form method="post" action="{{ route('complaints.status',$c) }}" class="action-strip">@csrf<select name="status"><option>open</option><option>under_review</option><option>rework</option><option>closed</option><option>reopened</option></select><button class="btn secondary small">Update complaint</button></form>
<form method="post" action="{{ route('reworks.store',$c) }}" class="subcard">@csrf<div class="grid"><div class="col-4 field"><label>Applicator</label><select name="assigned_applicator_id" required>@foreach($applicators as $u)<option value="{{ $u->id }}" @selected($workOrder->applicator_id===$u->id)>{{ $u->name }} · {{ $u->open_work_count }} open</option>@endforeach</select></div><div class="col-4 field"><label>Corrective action</label><input name="corrective_action"></div><div class="col-2 field"><label>Film qty</label><input type="number" step="0.01" name="film_quantity"></div><div class="col-2 field"><label>Unit</label><input name="film_unit" placeholder="m / sq.ft"></div></div><button class="btn small">Create rework</button></form>
@foreach($c->reworks as $r)<div class="rework-row"><div><strong>{{ $r->reference }}</strong> <span class="badge">{{ $r->status }}</span><br><span class="muted">{{ str_replace('_',' ',$r->scope_classification) }} · Applicator {{ $r->applicator?->name ?? '—' }}</span>@if($r->linkedNewWorkOrder)<br><a href="{{ route('work-orders.show',$r->linkedNewWorkOrder) }}">Linked new work: {{ $r->linkedNewWorkOrder->work_order_number }}</a>@endif</div>@if(auth()->user()->role?->slug==='super_admin'||auth()->user()->hasPermission('work.change_rework_scope'))<form method="post" action="{{ route('reworks.scope',$r) }}">@csrf<div class="stack"><select name="scope_classification"><option value="in_scope_rework" @selected($r->scope_classification==='in_scope_rework')>Inside original scope</option><option value="out_of_scope_new_work" @selected($r->scope_classification==='out_of_scope_new_work')>Outside scope → create linked new work</option></select><select name="applicator_id"><option value="">Keep/select later</option>@foreach($applicators as $u)<option value="{{ $u->id }}">{{ $u->name }} · {{ $u->open_work_count }} open</option>@endforeach</select></div><textarea name="notes" placeholder="Mandatory reason for scope decision" required></textarea><button class="btn secondary small">Apply scope decision</button></form>@endif</div>@endforeach</div>@endforeach</div>@endif</div>
@endif

@if($payment)<div class="card"><div class="card-head"><div><h2>Payment ledger</h2><p class="muted">Rework never silently rewrites a paid original payment.</p></div><span class="badge large">{{ $payment->status==='paid' && $payment->mode==='status_based_approval' ? 'DONE' : strtoupper($payment->status) }}</span></div><div class="detail-grid"><div><small>Eligible</small><strong>{{ $payment->currency }} {{ number_format($payment->eligible_amount,2) }}</strong></div><div><small>Paid</small><strong>{{ $payment->paid_amount ? $payment->currency.' '.number_format($payment->paid_amount,2) : '—' }}</strong></div><div><small>Reference</small><strong>{{ $payment->reference ?: '—' }}</strong></div><div><small>Previous status</small><strong>{{ $payment->previous_status ?: '—' }}</strong></div></div>@if(auth()->user()->role?->slug==='super_admin'||auth()->user()->hasPermission('payment.revert'))<form method="post" action="{{ route('payments.revert',$payment) }}" class="subcard">@csrf<h3>Privileged payment status correction</h3><div class="grid"><div class="col-4 field"><label>Target</label><select name="target_status"><option value="eligible">eligible</option><option value="held">held</option><option value="reversed">reversed</option></select></div><div class="col-4 field"><label>Reason</label><select name="reason_id" required>@foreach($reasons->where('category','payment') as $r)<option value="{{ $r->id }}">{{ $r->label }}</option>@endforeach</select></div><div class="col-12 field"><label>Notes</label><textarea name="notes" required></textarea></div></div><button class="btn danger small">Change payment status</button></form>@endif</div>@endif

<div class="plugin-slot">{!! $pr->renderSlot('work.show.before_timeline',$pluginCtx,auth()->user()) !!}</div>
<div class="card"><h2>Immutable work history</h2><div class="timeline">@foreach($workOrder->events->sortByDesc('created_at') as $e)<div class="event"><strong>{{ $e->event_type }}</strong><p>{{ $e->message }}</p><small>{{ optional($e->created_at)->format('d M Y H:i:s') }} · Actor #{{ $e->actor_id }} @if($e->from_status || $e->to_status) · {{ $e->from_status }} → {{ $e->to_status }} @endif</small></div>@endforeach</div></div>
<div class="plugin-slot">{!! $pr->renderSlot('work.show.after_timeline',$pluginCtx,auth()->user()) !!}</div>
</div>

<div class="col-4 side-column"><div class="plugin-slot">{!! $pr->renderSlot('work.show.sidebar.top',$pluginCtx,auth()->user()) !!}</div>
@if(auth()->user()->hasPermission('work.delegate'))<div class="card"><h3>Delegate to Zonal Manager</h3><form method="post" action="{{ route('work-orders.delegate',$workOrder) }}">@csrf<div class="field"><select name="zonal_manager_id"><option value="">Select manager</option>@foreach($zonalManagers as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div><div class="field"><textarea name="notes" placeholder="Delegation notes"></textarea></div><button class="btn wide">Delegate</button></form></div>@endif
@if(auth()->user()->hasPermission('work.assign_applicator'))<div class="card"><h3>Assign / reassign Applicator</h3><p class="muted">Only Applicators mapped to this work zone are listed. Open load is shown before assignment.</p><form method="post" action="{{ route('work-orders.assign',$workOrder) }}">@csrf<div class="field"><select name="applicator_id" required><option value="">Select applicator</option>@foreach($applicators as $u)<option value="{{ $u->id }}" @selected($workOrder->applicator_id===$u->id)>{{ $u->name }} — {{ $u->open_work_count }} open {{ $u->pincode ? '· PIN '.$u->pincode : '' }}</option>@endforeach</select></div><div class="field"><select name="reason_id"><option value="">Reason (optional first assignment)</option>@foreach($reasons->where('category','reassignment') as $r)<option value="{{ $r->id }}">{{ $r->label }}</option>@endforeach</select></div><div class="field"><textarea name="notes" placeholder="Reason details"></textarea></div><button class="btn wide">Save assignment</button></form></div>@endif
@if(auth()->user()->hasPermission('work.assign_verifier'))<div class="card"><h3>External verifier</h3><form method="post" action="{{ route('work-orders.verifier',$workOrder) }}">@csrf<div class="field"><select name="external_verifier_id"><option value="">Select verifier</option>@foreach($verifiers as $u)<option value="{{ $u->id }}" @selected($workOrder->external_verifier_id===$u->id)>{{ $u->name }} @if($u->designation)· {{ $u->designation }}@endif @if($u->showroom)· {{ $u->showroom->name }}@endif</option>@endforeach</select></div><button class="btn wide">Assign verifier</button></form></div>@endif@if(auth()->user()->role?->slug==='super_admin'||auth()->user()->hasPermission('work.override'))<div class="card"><h3>Public tracking URL</h3><p class="muted">Anyone holding this random URL can see read-only job progress. Evidence, chat, contacts, OTP and payment stay private.</p>@if($workOrder->tracking_enabled && $workOrder->tracking_token)<div class="field"><input readonly value="{{ route('tracking.show',$workOrder->tracking_token) }}" onclick="this.select()"></div><a class="btn secondary wide" target="_blank" href="{{ route('tracking.show',$workOrder->tracking_token) }}">Open tracker ↗</a>@endif<div class="action-strip"><form method="post" action="{{ route('work-orders.tracking.toggle',$workOrder) }}">@csrf<input type="hidden" name="tracking_enabled" value="{{ $workOrder->tracking_enabled?0:1 }}"><button class="btn secondary small">{{ $workOrder->tracking_enabled?'Disable':'Enable' }} tracker</button></form><form method="post" action="{{ route('work-orders.tracking.regenerate',$workOrder) }}" onsubmit="return confirm('Regenerate tracker URL? Old link will stop working.')">@csrf<button class="btn danger small">Regenerate URL</button></form></div></div>@endif
@if(auth()->user()->role?->slug==='external_verifier'||auth()->user()->role?->slug==='super_admin'||auth()->user()->hasPermission('work.disapprove')||auth()->user()->hasPermission('work.approve'))<div class="card"><h3>Review / approval</h3>@if(auth()->user()->role?->slug==='external_verifier' && auth()->user()->approval_otp_required)<div class="alert warning">Every showroom/external verifier decision is confirmed with a one-time code sent to <strong>{{ auth()->user()->email }}</strong>.</div><form method="post" action="{{ route('work-orders.review-otp',$workOrder) }}" class="action-strip">@csrf<button class="btn secondary wide">Send / resend review OTP</button></form>@endif<form method="post" action="{{ route('work-orders.review',$workOrder) }}">@csrf<div class="field"><label>Decision</label><select name="decision"><option value="approve">Approve</option><option value="return">Return for correction</option><option value="quality_hold">Quality hold</option><option value="reject">Reject</option></select></div><div class="field"><label>Reason</label><select name="reason_id"><option value="">Select if applicable</option>@foreach($reasons as $r)<option value="{{ $r->id }}">{{ $r->category }} — {{ $r->label }}</option>@endforeach</select></div><div class="field"><label>Comments</label><textarea name="comments"></textarea></div>@if(auth()->user()->role?->slug==='external_verifier' && auth()->user()->approval_otp_required)<div class="field"><label>Email OTP *</label><input name="email_otp" maxlength="6" inputmode="numeric" pattern="[0-9]{6}" placeholder="6-digit code" required><small class="muted">OTP is single-use and tied to this work order.</small></div>@endif<button class="btn good wide">Confirm & record review</button></form></div>@endif
<div class="plugin-slot">{!! $pr->renderSlot('work.show.sidebar.bottom',$pluginCtx,auth()->user()) !!}</div>
</div>
</div>
@endsection
@push('scripts')
<script>
const activeCameraStreams=new WeakMap();
async function openEvidenceCamera(btn){const form=btn.closest('form'),box=form.querySelector('.camera-box'),video=box.querySelector('video'),file=form.querySelector('.camera-file-fallback'),state=form.querySelector('.camera-state');if(!navigator.mediaDevices?.getUserMedia){file.hidden=false;file.click();return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});activeCameraStreams.set(form,stream);video.srcObject=stream;box.hidden=false;state.textContent='Camera ready';}catch(e){file.hidden=false;file.click();state.textContent='Live camera unavailable — browser capture fallback';}}
function closeEvidenceCamera(btn){const form=btn.closest('form'),box=form.querySelector('.camera-box'),stream=activeCameraStreams.get(form);stream?.getTracks().forEach(t=>t.stop());activeCameraStreams.delete(form);box.hidden=true;}
function captureEvidenceCamera(btn){const form=btn.closest('form'),video=form.querySelector('video'),file=form.querySelector('.camera-file-fallback'),preview=form.querySelector('.camera-preview'),state=form.querySelector('.camera-state');if(!video.videoWidth)return;const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;c.getContext('2d').drawImage(video,0,0);c.toBlob(blob=>{if(!blob)return;const f=new File([blob],`scratchgard-${Date.now()}.jpg`,{type:'image/jpeg'});const dt=new DataTransfer();dt.items.add(f);file.files=dt.files;preview.src=URL.createObjectURL(blob);preview.hidden=false;state.textContent='Photo captured — ready to upload';closeEvidenceCamera(btn);},'image/jpeg',0.92);}
document.addEventListener('change',e=>{if(e.target.matches('.camera-file-fallback')&&e.target.files?.[0]){const form=e.target.closest('form'),preview=form.querySelector('.camera-preview'),state=form.querySelector('.camera-state');preview.src=URL.createObjectURL(e.target.files[0]);preview.hidden=false;state.textContent='Photo selected from browser camera control';}});
function attachLocation(form,ev){if(!navigator.geolocation)return true;if(ev)ev.preventDefault();navigator.geolocation.getCurrentPosition(pos=>{const lat=form.querySelector('[name=latitude]'),lng=form.querySelector('[name=longitude]');if(lat)lat.value=pos.coords.latitude;if(lng)lng.value=pos.coords.longitude;const acc=form.querySelector('[name=accuracy]')||form.querySelector('[name=gps_accuracy]');if(acc)acc.value=pos.coords.accuracy||'';form.submit()},()=>{if(confirm('Location could not be captured. Continue and let the server enforce exception policy?'))form.submit()},{enableHighAccuracy:true,timeout:12000,maximumAge:0});return false}
</script>
@endpush
