@extends('layouts.app')
@section('title','My Profile')
@section('content')
@php($profileCtx=['user'=>$user])
<div class="page-head"><div><p class="eyebrow">Account</p><h1>My profile</h1><p class="muted">Username can be changed if available. Contact changes activate only after OTP verification. PIN changes are re-resolved against exact zone PIN mappings.</p></div></div>
<div class="plugin-slot">{!! app(\App\Plugins\PluginRuntime::class)->renderSlot('profile.before',$profileCtx,auth()->user()) !!}</div>
@if($user->role?->slug==='external_verifier')<div class="card"><h2>Showroom verifier profile</h2><div class="detail-grid"><div><small>Vendor</small><strong>{{ $user->showroom?->vendor?->name ?? '—' }}</strong></div><div><small>Showroom</small><strong>{{ $user->showroom?->name ?? '—' }}</strong></div><div><small>Designation</small><strong>{{ $user->designation ?: 'Showroom / Quality Manager' }}</strong></div><div><small>Review security</small><strong>{{ $user->approval_otp_required ? 'Email OTP required' : 'Standard login confirmation' }}</strong></div></div><p class="muted">Showroom scope is controlled by Scratchgard. Contact information can be updated below; changed email/mobile activates only after OTP verification.</p></div>@endif
<form method="post" action="{{ route('profile.update') }}" enctype="multipart/form-data" class="card">@csrf @method('PUT')
<div class="grid">
<div class="col-6 field"><label>Name</label><input name="name" value="{{ old('name',$user->name) }}" required></div>
<div class="col-6 field"><label>Username</label><input id="profileUsername" name="username" value="{{ old('username',$user->username) }}" maxlength="30" required><small id="profileUsernameStatus" class="muted">Use this, email, or mobile to sign in.</small></div>
<div class="col-6 field"><label>Email</label><input type="email" name="email" value="{{ old('email',$user->pending_email ?: $user->email) }}"><small class="muted">Verified: {{ $user->email_verified_at?'Yes':'No' }} · normalized to lowercase</small></div>
<div class="col-2 field"><label>Country code</label><input name="mobile_country_code" value="{{ old('mobile_country_code',$user->mobile_country_code ?: $defaultCountryCode) }}" maxlength="5" inputmode="tel"></div>
<div class="col-4 field"><label>Mobile</label><input name="mobile" value="{{ old('mobile',$user->mobile_national_number ?: ($user->pending_mobile ? substr(preg_replace('/\D/','',$user->pending_mobile),-10) : '')) }}" maxlength="10" pattern="[0-9]{10}" inputmode="numeric"><small class="muted">Exactly 10 digits · Verified: {{ $user->mobile_verified_at?'Yes':'No' }}</small></div>
<div class="col-3 field"><label>PIN</label><input id="profilePin" name="pincode" maxlength="6" inputmode="numeric" value="{{ old('pincode',$user->pincode) }}" required></div><div class="col-9 field"><label>Address</label><textarea name="address" required>{{ old('address',$user->address) }}</textarea></div>
<div class="col-6 field"><label>Primary zone</label><select name="zone_id" id="profileZone" @disabled(!$zoneSelectionAllowed)><option value="{{ $user->primary_zone_id }}">{{ $user->primaryZone?->code }} — {{ $user->primaryZone?->name }}</option></select>@if(!$zoneSelectionAllowed)<small class="muted">Zone is auto-selected by exact PIN mapping under current policy.</small>@endif</div><div class="col-6 field"><label>Profile picture</label><input type="file" name="profile_photo" accept="image/*" capture="user"></div>
@include('plugins.partials.form-fields',['formName'=>'user.profile','context'=>$profileCtx])
</div><button class="btn">Save profile</button></form>
@if($user->pending_email || $user->pending_mobile)<form class="card" method="post" action="{{ route('profile.verify') }}">@csrf<h2>Verify pending contact change</h2><div class="grid">@if($user->pending_email)<div class="col-6 field"><label>Email OTP for {{ $user->pending_email }}</label><input name="email_code" maxlength="6" inputmode="numeric"></div>@endif @if($user->pending_mobile)<div class="col-6 field"><label>Mobile OTP for {{ $user->pending_mobile }}</label><input name="mobile_code" maxlength="6" inputmode="numeric"></div>@endif</div><button class="btn secondary">Verify change</button></form>@endif
@include('plugins.partials.tabs',['screen'=>'profile.show','context'=>$profileCtx])
<div class="plugin-slot">{!! app(\App\Plugins\PluginRuntime::class)->renderSlot('profile.after',$profileCtx,auth()->user()) !!}</div>
@endsection
@push('scripts')<script>
const p=document.getElementById('profilePin'),z=document.getElementById('profileZone');let t;async function load(){if(p.value.length!==6)return;const u=new URL('{{ route('profile.zone') }}',location.origin);u.searchParams.set('pincode',p.value);const d=await fetch(u).then(r=>r.json());if(z&&!z.disabled)z.innerHTML=d.matches.map(x=>`<option value="${x.zone_id}">${x.code} — ${x.name}</option>`).join('')}p.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(load,350)});
const un=document.getElementById('profileUsername'),us=document.getElementById('profileUsernameStatus');let ut;async function checkU(){const v=un.value.trim();if(!v)return;const u=new URL('{{ route('profile.username') }}',location.origin);u.searchParams.set('username',v);const d=await fetch(u).then(r=>r.json());if(d.normalized&&d.normalized!==un.value)un.value=d.normalized;us.textContent=d.message;us.className=d.available?'good-text':'text-danger'}un.addEventListener('input',()=>{clearTimeout(ut);ut=setTimeout(checkU,300)});
</script>@endpush
