@extends('layouts.app')
@section('title','Zones & Locations')
@section('content')
<div class="page-head"><div><p class="eyebrow">Operations master data</p><h1>Zones, India Post Locations, Vendors & Showrooms</h1><p class="muted">Import the postal directory once. State/District/Locality are only filters: Scratchgard stores the resulting exact 6-digit PIN memberships inside each zone. This avoids spelling/renaming problems such as Odisha/Orissa. Overlaps are allowed and shown.</p></div><div class="pill">{{ number_format($postalCount) }} postal rows</div></div>

<div class="grid">
<div class="col-5 card"><h2>Create zone</h2><form method="post" action="{{ route('masters.zones.store') }}">@csrf<div class="field"><label>Zone name</label><input name="name" placeholder="Kanpur Central" required></div><div class="field"><label>Short code</label><input name="code" placeholder="KNP-C" required></div><button class="btn">Create zone</button></form></div>
<div class="col-7 card"><h2>Import India Post / OGD postal CSV</h2><p class="muted">No runtime location API is required. Supported headers include pincode, officename, statename, districtname, taluk/city/locality, divisionname, regionname, circlename, latitude and longitude.</p><form method="post" action="{{ route('masters.postal.import') }}" enctype="multipart/form-data">@csrf<div class="stack"><input type="file" name="csv" accept=".csv,text/csv" required><button class="btn secondary">Import / refresh postal master</button></div></form><p class="hint">Source guidance is included in docs/LOCATION_DATA_SETUP.md.</p></div>
</div>

<div class="card"><div class="card-head"><div><h2>PIN-based zone builder</h2><p class="muted">Select State, District, City/Locality or one PIN from the imported postal master. The selection is immediately materialized into exact PIN assignments; names are not used later to resolve zones.</p></div></div>
<form method="post" action="{{ route('masters.coverage.store') }}" id="coverageForm">@csrf
<div class="grid">
<div class="col-3 field"><label>Zone</label><select name="zone_id" required>@foreach($zones->where('status','active') as $z)<option value="{{ $z->id }}">{{ $z->code }} — {{ $z->name }}</option>@endforeach</select></div>
<div class="col-2 field"><label>Scope</label><select name="scope_type" id="scopeType"><option value="state">State</option><option value="district">District</option><option value="city">City / locality</option><option value="pincode">PIN code</option></select></div>
<div class="col-3 field loc-state"><label>State</label><select name="state" id="stateSel"><option value="">Select state</option>@foreach($states as $s)<option>{{ $s }}</option>@endforeach</select></div>
<div class="col-3 field loc-district"><label>District</label><select name="district" id="districtSel"><option value="">Select district</option></select></div>
<div class="col-3 field loc-city"><label>City / locality</label><select name="city" id="citySel"><option value="">Select city/locality</option></select></div>
<div class="col-3 field loc-pin"><label>PIN</label><input name="pincode" id="pinInput" maxlength="6" inputmode="numeric"></div>

</div><div id="overlapPreview" class="alert warning" style="display:none"></div><button class="btn">Build zone from exact PINs</button></form></div>

<div class="card"><h2>PIN mapping batches & overlap visibility</h2><p class="muted">Each row records what admin selected, but the actual zone membership is stored as exact PIN codes. Removing a batch removes only the PIN assignments created by that batch; overlapping assignments from other batches remain.</p><div class="table-wrap"><table><thead><tr><th>Zone</th><th>Selection source</th><th>Selected geography</th><th>PINs materialized</th><th>Action</th></tr></thead><tbody>@forelse($mappingBatches as $b)<tr><td><strong>{{ $b->zone?->code }}</strong><br><span class="muted">{{ $b->zone?->name }}</span></td><td><span class="badge">{{ strtoupper($b->source_scope) }}</span></td><td>{{ collect([$b->source_state,$b->source_district,$b->source_city,$b->source_pincode])->filter()->implode(' → ') }}</td><td>{{ number_format($b->pincode_count) }}</td><td>@if(auth()->user()->role?->slug==='super_admin')<form method="post" action="{{ route('masters.zone-mappings.delete',$b) }}" onsubmit="return confirm('Remove this mapping batch? Only its PIN assignments will be removed.')">@csrf @method('DELETE')<button class="btn danger small">Remove mapping</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="muted">No PIN-based zone mappings yet.</td></tr>@endforelse</tbody></table></div></div>

<div class="card"><h2>Zones</h2><div class="zone-grid">@foreach($zones as $z)<div class="subcard"><div class="stack between"><div><strong>{{ $z->code }}</strong><div>{{ $z->name }}</div><small class="muted">{{ $z->pin_assignments_count }} exact PIN assignments · {{ $z->mapping_batches_count }} mapping batches · {{ $z->pincodes_count }} legacy mappings</small></div><span class="badge">{{ $z->status }}</span></div>@if(auth()->user()->role?->slug==='super_admin')<form method="post" action="{{ route('masters.zones.update',$z) }}" class="compact-form">@csrf @method('PUT')<input name="name" value="{{ $z->name }}"><input name="code" value="{{ $z->code }}"><select name="status"><option @selected($z->status==='active')>active</option><option @selected($z->status==='archived')>archived</option></select><button class="btn secondary small">Save</button></form><form method="post" action="{{ route('masters.zones.delete',$z) }}" onsubmit="return confirm('Archive/delete this zone? Historical zones are archived, not destroyed.')">@csrf @method('DELETE')<button class="text-danger">Archive / delete</button></form>@endif</div>@endforeach</div></div>

<div class="grid">
<div class="col-5 card"><h2>Create vendor / dealer</h2><form method="post" action="{{ route('masters.vendors.store') }}">@csrf<div class="field"><label>Name</label><input name="name" placeholder="Tata Motors" required></div><div class="field"><label>Code</label><input name="code" placeholder="TATA" required></div><button class="btn">Create vendor</button></form></div>
<div class="col-7 card" id="showrooms"><h2>Create showroom / branch</h2><form method="post" action="{{ route('masters.showrooms.store') }}">@csrf<div class="grid"><div class="col-6 field"><label>Vendor</label><select name="vendor_organization_id">@foreach($vendors as $v)<option value="{{ $v->id }}">{{ $v->name }}</option>@endforeach</select></div><div class="col-6 field"><label>Zone override (optional)</label><select name="zone_id"><option value="">Auto from PIN</option>@foreach($zones->where('status','active') as $z)<option value="{{ $z->id }}">{{ $z->code }}</option>@endforeach</select></div><div class="col-6 field"><label>Name</label><input name="name" required></div><div class="col-6 field"><label>Code</label><input name="code" required></div><div class="col-12 field"><label>Address</label><textarea name="address" required></textarea></div><div class="col-4 field"><label>PIN</label><input name="pincode" maxlength="6" inputmode="numeric" required></div><div class="col-4 field"><label>Latitude</label><input name="latitude"></div><div class="col-4 field"><label>Longitude</label><input name="longitude"></div><div class="col-4 field"><label>Geofence metres</label><input type="number" name="geofence_radius_m" value="250"></div></div><button class="btn">Create showroom</button></form></div>
</div>
<div class="card"><h2>Showrooms</h2><div class="table-wrap"><table><thead><tr><th>Vendor</th><th>Showroom</th><th>PIN</th><th>Zone</th><th>Geofence</th></tr></thead><tbody>@foreach($showrooms as $s)<tr><td>{{ $s->vendor?->name }}</td><td>{{ $s->name }}<br><span class="muted">{{ $s->code }}</span></td><td>{{ $s->pincode }}</td><td>{{ $s->zone?->code }}</td><td>{{ $s->geofence_radius_m }} m</td></tr>@endforeach</tbody></table></div></div>
@endsection
@push('scripts')
<script>
const scope=document.getElementById('scopeType'), state=document.getElementById('stateSel'), district=document.getElementById('districtSel'), city=document.getElementById('citySel');
async function opts(type, params={}){const u=new URL('{{ route('masters.locations') }}',location.origin);u.searchParams.set('type',type);Object.entries(params).forEach(([k,v])=>v&&u.searchParams.set(k,v));return fetch(u).then(r=>r.json())}
function fill(sel, values, label){sel.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option>${String(v).replaceAll('&','&amp;').replaceAll('<','&lt;')}</option>`).join('')}
async function loadDistricts(){fill(district,await opts('district',{state:state.value}),'Select district');fill(city,[],'Select city/locality')}
async function loadCities(){fill(city,await opts('city',{state:state.value,district:district.value}),'Select city/locality')}
state.addEventListener('change',async()=>{await loadDistricts();previewOverlap()});district.addEventListener('change',async()=>{await loadCities();previewOverlap()});city.addEventListener('change',previewOverlap);document.getElementById('pinInput').addEventListener('input',()=>{clearTimeout(window.__ov);window.__ov=setTimeout(previewOverlap,300)});
function toggle(){const s=scope.value;document.querySelector('.loc-state').style.display=s==='pincode'?'none':'block';document.querySelector('.loc-district').style.display=['district','city'].includes(s)?'block':'none';document.querySelector('.loc-city').style.display=s==='city'?'block':'none';document.querySelector('.loc-pin').style.display=s==='pincode'?'block':'none';previewOverlap()}
async function previewOverlap(){const box=document.getElementById('overlapPreview'),s=scope.value,pin=document.getElementById('pinInput').value;const u=new URL('{{ route('masters.coverage.preview') }}',location.origin);u.searchParams.set('scope_type',s);if(state.value)u.searchParams.set('state',state.value);if(district.value)u.searchParams.set('district',district.value);if(city.value)u.searchParams.set('city',city.value);if(pin)u.searchParams.set('pincode',pin);try{const d=await fetch(u).then(r=>r.ok?r.json():({zones:[]}));const count=d.pincode_count||0;if(d.zones?.length){box.style.display='block';box.innerHTML=`<strong>${count} exact PINs will be mapped. Overlap allowed with:</strong> `+d.zones.map(z=>`<span class="pill">${z.code} · ${z.name} (${z.overlap_count||0} PIN overlaps)</span>`).join(' ')}else if(count){box.style.display='block';box.innerHTML=`<strong>${count} exact PINs will be mapped.</strong> No overlap with another zone.`}else{box.style.display='none';box.textContent=''}}catch(e){box.style.display='none'}}
scope.addEventListener('change',toggle);toggle();
</script>
@endpush
