@extends('layouts.app')
@section('title',$ticket->ticket_number)
@section('content')
@php($ticketCtx=['ticket'=>$ticket])
<div class="plugin-slot">{!! app(\App\Plugins\PluginRuntime::class)->renderSlot('ticket.show.before',$ticketCtx,auth()->user()) !!}</div>
<div class="page-head"><div><p class="eyebrow">{{ $ticket->ticket_number }}</p><h1>{{ $ticket->subject }}</h1><p class="muted">{{ $ticket->category }} · Priority {{ $ticket->priority }} @if($ticket->workOrder)· <a href="{{ route('work-orders.show',$ticket->workOrder) }}">{{ $ticket->workOrder->work_order_number }}</a>@endif</p></div><span class="badge large">{{ $ticket->status }}</span></div>
<div class="grid"><div class="col-8"><div class="card"><p>{{ $ticket->description }}</p></div><div class="card"><h2>Conversation</h2><div class="conversation">@foreach($ticket->messages as $m)@if(!$m->internal_only || auth()->user()->role?->is_internal)<div class="message"><div class="avatar">{{ strtoupper(substr($m->sender?->name ?? '?',0,1)) }}</div><div><div class="message-head"><strong>{{ $m->sender?->name }}</strong><small>{{ $m->created_at->diffForHumans() }} @if($m->internal_only)· Internal note@endif</small></div><p>{{ $m->message }}</p>@if($m->attachments)<div class="attachment-list">@foreach($m->attachments as $i=>$a)<a class="pill" href="{{ route('tickets.attachment',['ticket'=>$ticket,'message'=>$m,'index'=>$i]) }}">{{ $a['name'] ?? 'Attachment' }}</a>@endforeach</div>@endif</div></div>@endif @endforeach</div><form method="post" enctype="multipart/form-data" action="{{ route('tickets.message',$ticket) }}">@csrf<div class="field"><textarea name="message" placeholder="Reply to ticket…" required></textarea></div><div class="field"><label>Attachments (optional, up to 5 × 10 MB)</label><input type="file" name="attachments[]" multiple></div><div class="grid">@include('plugins.partials.form-fields',['formName'=>'ticket.reply','context'=>$ticketCtx])</div>@if(auth()->user()->role?->is_internal)<label class="check"><input type="checkbox" name="internal_only" value="1"> Internal-only note</label>@endif<button class="btn">Send reply</button></form></div>
<div class="plugin-slot">{!! app(\App\Plugins\PluginRuntime::class)->renderSlot('ticket.show.after_conversation',$ticketCtx,auth()->user()) !!}</div>@include('plugins.partials.tabs',['screen'=>'ticket.show','context'=>$ticketCtx])</div><div class="col-4"><div class="plugin-slot">{!! app(\App\Plugins\PluginRuntime::class)->renderSlot('ticket.show.sidebar.top',$ticketCtx,auth()->user()) !!}</div><div class="card"><h2>People</h2><p><b>Raised by</b><br>{{ $ticket->raiser?->name }}</p><p><b>Assigned to</b><br>{{ $ticket->assignee?->name ?? 'Unassigned' }}</p><p><b>Participants</b><br>{{ $ticket->participants->pluck('name')->join(', ') }}</p></div>@if(auth()->user()->role?->slug==='super_admin'||auth()->user()->hasPermission('tickets.manage'))<form class="card" method="post" action="{{ route('tickets.status',$ticket) }}">@csrf<h2>Manage ticket</h2><div class="field"><label>Status</label><select name="status">@foreach(['open','in_progress','waiting_user','resolved','closed','reopened'] as $s)<option @selected($ticket->status===$s)>{{ $s }}</option>@endforeach</select></div><div class="field"><label>Assign to</label><select name="assigned_to"><option value="">Keep/unassigned</option>@foreach($users as $u)<option value="{{ $u->id }}" @selected($ticket->assigned_to===$u->id)>{{ $u->name }}</option>@endforeach</select></div><div class="field"><label>Reason / notes</label><textarea name="notes"></textarea></div><button class="btn secondary">Update ticket</button></form>@endif<div class="plugin-slot">{!! app(\App\Plugins\PluginRuntime::class)->renderSlot('ticket.show.sidebar.bottom',$ticketCtx,auth()->user()) !!}</div></div></div>
@endsection
