<?php
return [
    'slots' => [
        'layout.head' => 'Inside <head>; trusted plugin styles/meta only.',
        'layout.after_topbar' => 'Immediately below the main top bar.',
        'layout.before_content' => 'Before the page content container.',
        'layout.after_content' => 'After page content, before footer.',
        'layout.before_footer' => 'Immediately before the site footer.',
        'dashboard.before_metrics' => 'Dashboard above core metrics.',
        'dashboard.after_metrics' => 'Dashboard below core metrics.',
        'dashboard.before_recent_work' => 'Dashboard before recent-work table.',
        'dashboard.after_recent_work' => 'Dashboard after recent-work table.',
        'work.show.before' => 'Work Order page before header.',
        'work.show.header.actions' => 'Additional actions next to tracker/directions.',
        'work.show.after_field_hero' => 'After Applicator vehicle/location hero.',
        'work.show.after_vehicle' => 'After vehicle/job card.',
        'work.show.before_field_execution' => 'Before field execution controls.',
        'work.show.after_field_execution' => 'After field execution controls.',
        'work.show.before_evidence' => 'Before evidence checklist/list.',
        'work.show.after_evidence' => 'After evidence list.',
        'work.show.before_conversation' => 'Before Work Order conversation.',
        'work.show.after_conversation' => 'After Work Order conversation.',
        'work.show.before_timeline' => 'Before immutable history.',
        'work.show.after_timeline' => 'After immutable history.',
        'work.show.sidebar.top' => 'Top of Work Order sidebar.',
        'work.show.sidebar.bottom' => 'Bottom of Work Order sidebar.',
        'work.index.before_filters' => 'Work list before search/filter area.',
        'work.index.after_table' => 'Work list after core table.',
        'profile.before' => 'Profile page before core form.',
        'profile.after' => 'Profile page after core forms.',
        'users.index.before_create' => 'Users page before create-user form.',
        'users.index.after_table' => 'Users page after existing-user table.',
        'payment.index.before_table' => 'Payments page before finance table.',
        'payment.index.after_table' => 'Payments page after finance table.',
        'ticket.show.before' => 'Ticket page before header/content.',
        'ticket.show.after_conversation' => 'Ticket after conversation/reply.',
        'ticket.show.sidebar.top' => 'Ticket sidebar top.',
        'ticket.show.sidebar.bottom' => 'Ticket sidebar bottom.',
    ],
    'tabs' => [
        'work.show' => 'Additional tab/section on a Work Order.',
        'profile.show' => 'Additional profile tab/section.',
        'ticket.show' => 'Additional ticket tab/section.',
    ],
    'forms' => [
        'user.create' => 'Fields inside Super Admin create-user form.',
        'user.profile' => 'Fields inside self-service profile form.',
        'work.create' => 'Fields inside Work Order creation form.',
        'ticket.reply' => 'Fields inside ticket reply form.',
    ],
    'tables' => [
        'work_orders' => 'Work Order list table.',
        'users' => 'User list table.',
        'payments' => 'Payment list table.',
    ],
];
