<?php
namespace App\Http\Controllers;

use App\Models\KycRecord;
use App\Models\Permission;
use App\Models\Role;
use App\Models\Setting;
use App\Models\User;
use App\Models\Zone;
use App\Models\Showroom;
use App\Models\VendorOrganization;
use App\Services\IdentityNormalizerService;
use App\Services\UserZoneService;
use App\Services\ZoneResolverService;
use App\Services\SystemNotificationService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use RuntimeException;
use App\Plugins\PluginRuntime;

class UserManagementController extends Controller
{
    public function index(Request $request){$users=User::with(['role','zones','primaryZone','showroom.vendor'])->latest();if($request->filled('role'))$users->whereHas('role',fn($q)=>$q->where('slug',$request->input('role')));if($request->filled('q')){$term=trim((string)$request->input('q'));$users->where(function($q)use($term){$q->where('name','like','%'.$term.'%')->orWhere('username','like','%'.$term.'%')->orWhere('email','like','%'.$term.'%')->orWhere('mobile','like','%'.$term.'%');});}return view('users.index',['users'=>$users->paginate(30)->withQueryString(),'roles'=>Role::orderBy('name')->get(),'zones'=>Zone::where('status','active')->orderBy('name')->get(),'showrooms'=>Showroom::with('vendor')->where('status','active')->orderBy('name')->get(),'vendors'=>VendorOrganization::where('status','active')->orderBy('name')->get(),'defaultCountryCode'=>(string)Setting::getValue('default_mobile_country_code','+91')]);}

    public function store(Request $request, UserZoneService $zoneService, ZoneResolverService $resolver, IdentityNormalizerService $identity, SystemNotificationService $notifications)
    {
        $email=$identity->normalizeEmail($request->input('email'));$username=$identity->normalizeUsername($request->input('username'));
        $rawMobile=trim((string)$request->input('mobile'));$mobileParts=$rawMobile!==''?$identity->normalizeMobile($rawMobile,$request->input('mobile_country_code'),(string)Setting::getValue('default_mobile_country_code','+91')):['country_code'=>null,'national_number'=>null,'canonical'=>null];
        $request->merge(['email'=>$email,'username'=>$username,'mobile'=>$mobileParts['canonical'],'mobile_country_code'=>$mobileParts['country_code'],'mobile_national_number'=>$mobileParts['national_number']]);
        $v=$request->validate(['role_id'=>'required|exists:roles,id','name'=>'required|string|max:120','username'=>'nullable|string|min:4|max:30|regex:/^(?=.*[a-z])[a-z0-9][a-z0-9._]*[a-z0-9]$/|unique:users,username','email'=>'nullable|email:rfc|max:190|unique:users,email','mobile'=>'nullable|string|max:30|unique:users,mobile','mobile_country_code'=>'nullable|string|max:8','mobile_national_number'=>'nullable|digits:10','password'=>'required|string|min:10','pincode'=>'nullable|string|max:12','address'=>'nullable|string|max:1000','employee_reference'=>'nullable|string|max:120','status'=>'required|in:verification_pending,pending,active,suspended,disabled','zones'=>'nullable|array','zones.*'=>'exists:zones,id','primary_zone_id'=>'nullable|exists:zones,id','allow_multiple_zones'=>'nullable|boolean','allow_zone_self_selection'=>'nullable|boolean','email_verified'=>'nullable|boolean','mobile_verified'=>'nullable|boolean','document_type'=>'nullable|string|max:80','document_number'=>'nullable|string|max:120','vendor_organization_id'=>'nullable|exists:vendor_organizations,id','showroom_id'=>'nullable|exists:showrooms,id','designation'=>'nullable|string|max:120','approval_otp_required'=>'nullable|boolean']);
        if(empty($v['email'])&&empty($v['mobile']))return back()->withInput()->withErrors(['email'=>'At least email or mobile is required.']);
        $role=Role::findOrFail($v['role_id']);if(in_array($role->slug,['zonal_manager','applicator'],true)&&empty($v['pincode']))return back()->withInput()->withErrors(['pincode'=>'PIN code is mandatory for Zonal Managers and Applicators.']);if($role->slug==='external_verifier'){if(empty($v['email']))return back()->withInput()->withErrors(['email'=>'Third-party showroom manager / external verifier requires a unique email for OTP-confirmed reviews.']);if(empty($v['showroom_id']))return back()->withInput()->withErrors(['showroom_id'=>'Assign the external verifier to a showroom, or create a designated temporary verifier account with a showroom before use.']);}$verifierShowroom=$role->slug==='external_verifier'&& !empty($v['showroom_id'])?Showroom::find($v['showroom_id']):null;
        $resolved=!empty($v['pincode'])?$resolver->resolvePincode($v['pincode']):null;$finalUsername=$v['username']??$identity->generateUsername($v['name']);
        $user=User::create(['role_id'=>$role->id,'name'=>$v['name'],'username'=>$finalUsername,'email'=>$v['email']??null,'mobile'=>$v['mobile']??null,'mobile_country_code'=>$v['mobile_country_code']??null,'mobile_national_number'=>$v['mobile_national_number']??null,'password'=>Hash::make($v['password']),'pincode'=>$v['pincode']??null,'address'=>$v['address']??null,'city'=>$resolved['postal']['city']??null,'district'=>$resolved['postal']['district']??null,'state'=>$resolved['postal']['state']??null,'country'=>'India','status'=>$v['status'],'employee_reference'=>$v['employee_reference']??null,'vendor_organization_id'=>$verifierShowroom?->vendor_organization_id ?? ($v['vendor_organization_id']??null),'showroom_id'=>$v['showroom_id']??null,'designation'=>$v['designation']??null,'approval_otp_required'=>$role->slug==='external_verifier'?$request->boolean('approval_otp_required'):false,'allow_multiple_zones'=>$request->boolean('allow_multiple_zones'),'allow_zone_self_selection'=>$request->has('allow_zone_self_selection')?$request->boolean('allow_zone_self_selection'):null,'email_verified_at'=>$request->boolean('email_verified')&&($v['email']??null)?now():null,'mobile_verified_at'=>$request->boolean('mobile_verified')&&($v['mobile']??null)?now():null]);
        $zoneIds=array_map('intval',$v['zones']??[]);if(!$zoneIds&&$resolved&&!empty($resolved['matches']))$zoneIds=[(int)$resolved['matches'][0]['zone_id']];
        if($zoneIds){try{$zoneService->assign($user,$zoneIds,auth()->user(),'admin',$v['primary_zone_id']??$zoneIds[0],$request->boolean('allow_multiple_zones'));}catch(RuntimeException $e){$user->delete();return back()->withInput()->withErrors(['zones'=>$e->getMessage()]);}}
        if(!empty($v['document_type'])||!empty($v['document_number']))KycRecord::create(['user_id'=>$user->id,'document_type'=>$v['document_type']??null,'document_number'=>$v['document_number']??null,'status'=>'submitted']);
        app(PluginRuntime::class)->doAction('user.admin.created',$user,(array)$request->input('plugin_fields',[]),auth()->user());
        try{$notifications->userRegistration($user,'USER_CREATED_BY_ADMIN','A Scratchgard user account was created for '.$user->name.' (@'.$user->username.'). Role: '.$role->name.'.');}catch(\Throwable $e){report($e);}
        return back()->with('status','User created. Username: '.$user->username.'. Default is one primary zone unless explicitly allowed otherwise.');
    }

    public function edit(User $user){$user->load(['role','zones','primaryZone','showroom.vendor']);return view('users.edit',['user'=>$user,'roles'=>Role::orderBy('name')->get(),'zones'=>Zone::where('status','active')->orderBy('name')->get(),'showrooms'=>Showroom::with('vendor')->where('status','active')->orderBy('name')->get(),'vendors'=>VendorOrganization::where('status','active')->orderBy('name')->get(),'permissions'=>Permission::where('slug','!=','plugins.manage')->orderBy('group')->orderBy('name')->get(),'overrides'=>DB::table('user_permission_overrides')->where('user_id',$user->id)->pluck('allowed','permission_id'),'defaultCountryCode'=>(string)Setting::getValue('default_mobile_country_code','+91')]);}

    public function update(Request $request, User $user, UserZoneService $zoneService, ZoneResolverService $resolver, IdentityNormalizerService $identity, SystemNotificationService $notifications)
    {
        $email=$identity->normalizeEmail($request->input('email'));$username=$identity->normalizeUsername($request->input('username'));
        $rawMobile=trim((string)$request->input('mobile'));$mobileParts=$rawMobile!==''?$identity->normalizeMobile($rawMobile,$request->input('mobile_country_code'),(string)Setting::getValue('default_mobile_country_code','+91')):['country_code'=>null,'national_number'=>null,'canonical'=>null];
        $request->merge(['email'=>$email,'username'=>$username,'mobile'=>$mobileParts['canonical'],'mobile_country_code'=>$mobileParts['country_code'],'mobile_national_number'=>$mobileParts['national_number']]);
        $v=$request->validate(['role_id'=>'required|exists:roles,id','name'=>'required|string|max:120','username'=>'required|string|min:4|max:30|regex:/^(?=.*[a-z])[a-z0-9][a-z0-9._]*[a-z0-9]$/|unique:users,username,'.$user->id,'email'=>'nullable|email:rfc|max:190|unique:users,email,'.$user->id,'mobile'=>'nullable|string|max:30|unique:users,mobile,'.$user->id,'mobile_country_code'=>'nullable|string|max:8','mobile_national_number'=>'nullable|digits:10','password'=>'nullable|string|min:10','pincode'=>'nullable|string|max:12','address'=>'nullable|string|max:1000','employee_reference'=>'nullable|string|max:120','status'=>'required|in:verification_pending,pending,active,suspended,disabled','zones'=>'nullable|array','zones.*'=>'exists:zones,id','primary_zone_id'=>'nullable|exists:zones,id','allow_multiple_zones'=>'nullable|boolean','allow_zone_self_selection'=>'nullable|boolean','email_verified'=>'nullable|boolean','mobile_verified'=>'nullable|boolean','grants'=>'nullable|array','grants.*'=>'exists:permissions,id','denies'=>'nullable|array','denies.*'=>'exists:permissions,id','vendor_organization_id'=>'nullable|exists:vendor_organizations,id','showroom_id'=>'nullable|exists:showrooms,id','designation'=>'nullable|string|max:120','approval_otp_required'=>'nullable|boolean']);
        if(empty($v['email'])&&empty($v['mobile']))return back()->withErrors(['email'=>'At least email or mobile is required.']);$role=Role::findOrFail($v['role_id']);if(in_array($role->slug,['zonal_manager','applicator'],true)&&empty($v['pincode']))return back()->withErrors(['pincode'=>'PIN code is mandatory.']);if($role->slug==='external_verifier'){if(empty($v['email']))return back()->withErrors(['email'=>'External verifier requires email for OTP review confirmation.']);if(empty($v['showroom_id']))return back()->withErrors(['showroom_id'=>'Assign this verifier to a showroom.']);}$verifierShowroom=$role->slug==='external_verifier'&& !empty($v['showroom_id'])?Showroom::find($v['showroom_id']):null;
        $resolved=!empty($v['pincode'])?$resolver->resolvePincode($v['pincode']):null;$data=['role_id'=>$v['role_id'],'name'=>$v['name'],'username'=>$v['username'],'email'=>$v['email']??null,'mobile'=>$v['mobile']??null,'mobile_country_code'=>$v['mobile_country_code']??null,'mobile_national_number'=>$v['mobile_national_number']??null,'pincode'=>$v['pincode']??null,'address'=>$v['address']??null,'city'=>$resolved['postal']['city']??$user->city,'district'=>$resolved['postal']['district']??$user->district,'state'=>$resolved['postal']['state']??$user->state,'employee_reference'=>$v['employee_reference']??null,'vendor_organization_id'=>$verifierShowroom?->vendor_organization_id ?? ($v['vendor_organization_id']??null),'showroom_id'=>$v['showroom_id']??null,'designation'=>$v['designation']??null,'approval_otp_required'=>$role->slug==='external_verifier'?$request->boolean('approval_otp_required'):false,'status'=>$v['status'],'allow_multiple_zones'=>$request->boolean('allow_multiple_zones'),'allow_zone_self_selection'=>$request->has('allow_zone_self_selection')?$request->boolean('allow_zone_self_selection'):null];
        if(!empty($v['password']))$data['password']=Hash::make($v['password']);if($request->boolean('email_verified')&&$v['email'])$data['email_verified_at']=$user->email_verified_at?:now();if(!$request->boolean('email_verified'))$data['email_verified_at']=null;if($request->boolean('mobile_verified')&&$v['mobile'])$data['mobile_verified_at']=$user->mobile_verified_at?:now();if(!$request->boolean('mobile_verified'))$data['mobile_verified_at']=null;$user->update($data);
        $zoneIds=array_map('intval',$v['zones']??[]);if(!$zoneIds&&$resolved&&!empty($resolved['matches']))$zoneIds=[(int)$resolved['matches'][0]['zone_id']];if($zoneIds)$zoneService->assign($user,$zoneIds,auth()->user(),'admin',$v['primary_zone_id']??$zoneIds[0],$request->boolean('allow_multiple_zones'));
        DB::transaction(function()use($request,$user){DB::table('user_permission_overrides')->where('user_id',$user->id)->delete();foreach($request->input('grants',[])as$pid)DB::table('user_permission_overrides')->insert(['user_id'=>$user->id,'permission_id'=>$pid,'allowed'=>1,'granted_by'=>auth()->id(),'reason'=>'Granted through user editor','created_at'=>now(),'updated_at'=>now()]);foreach($request->input('denies',[])as$pid)DB::table('user_permission_overrides')->insert(['user_id'=>$user->id,'permission_id'=>$pid,'allowed'=>0,'granted_by'=>auth()->id(),'reason'=>'Denied through user editor','created_at'=>now(),'updated_at'=>now()]);});
        app(PluginRuntime::class)->doAction('user.admin.updated',$user->fresh(),(array)$request->input('plugin_fields',[]),auth()->user());
        try{$notifications->userRegistration($user,'USER_PROFILE_UPDATED','Scratchgard account/profile was updated for '.$user->name.' (@'.$user->username.').');}catch(\Throwable $e){report($e);}
        return back()->with('status','User identity, zones, verification flags and permissions updated.');
    }
    public function destroy(User $user){abort_unless(auth()->user()->role?->slug==='super_admin',403);abort_if($user->id===auth()->id(),422,'You cannot delete your own Super Admin account.');$user->update(['status'=>'disabled']);return back()->with('status','User disabled. Historical operational records are preserved.');}
}
