@extends('layouts.app')
@section('title','Operational Configuration')
@section('content')
<h1>Operational Configuration</h1>
<div class="grid">
<div class="col-6 card"><h2>Add reason selector</h2><form method="post" action="{{ route('configuration.reasons.store') }}">@csrf<div class="grid"><div class="col-6 field"><label>Category</label><input name="category" placeholder="reassignment" required></div><div class="col-6 field"><label>Code</label><input name="code" placeholder="APPLICATOR_UNAVAILABLE" required></div><div class="col-12 field"><label>Label</label><input name="label" required></div><div class="col-6 field"><label>Target status</label><input name="target_status"></div><div class="col-6 field"><label>Payment effect</label><input name="payment_effect" placeholder="block / release"></div><div class="col-6"><label><input style="width:auto" type="checkbox" name="comment_required" value="1"> Comment required</label></div><div class="col-6"><label><input style="width:auto" type="checkbox" name="evidence_required" value="1"> Evidence required</label></div></div><br><button class="btn">Add reason</button></form></div>
<div class="col-6 card"><h2>Add pricing rule</h2><form method="post" action="{{ route('configuration.pricing.store') }}">@csrf<div class="grid"><div class="col-6 field"><label>Package code</label><input name="package_code" required></div><div class="col-6 field"><label>Zone (optional)</label><select name="zone_id"><option value="">All zones</option>@foreach($zones as $z)<option value="{{ $z->id }}">{{ $z->code }}</option>@endforeach</select></div><div class="col-6 field"><label>Vehicle category</label><input name="vehicle_category"></div><div class="col-3 field"><label>Amount</label><input type="number" step="0.01" name="amount" required></div><div class="col-3 field"><label>Currency</label><input name="currency" value="INR"></div><div class="col-6 field"><label>Effective from</label><input type="date" name="effective_from"></div><div class="col-6 field"><label>Effective to</label><input type="date" name="effective_to"></div></div><button class="btn">Add pricing</button></form></div>
</div>
<div class="card"><h2>Create evidence template</h2><form method="post" action="{{ route('configuration.templates.store') }}">@csrf<div class="grid"><div class="col-6 field"><label>Name</label><input name="name" required></div><div class="col-4 field"><label>Package code</label><input name="package_code" required></div><div class="col-2 field"><label>Version</label><input type="number" name="version" value="1"></div></div><button class="btn">Create template</button></form></div>
@foreach($templates as $t)
<div class="card"><h2>{{ $t->name }} <span class="badge">{{ $t->package_code }} v{{ $t->version }}</span></h2>
<table><thead><tr><th>Stage</th><th>Slot</th><th>Label</th><th>Mandatory</th><th>Hint</th></tr></thead><tbody>@foreach($t->slots->sortBy('sort_order') as $sl)<tr><td>{{ $sl->stage }}</td><td>{{ $sl->slot_code }}</td><td>{{ $sl->label }}</td><td>{{ $sl->mandatory?'Yes':'No' }}</td><td>{{ $sl->closeup_hint }}</td></tr>@endforeach</tbody></table>
<h3>Add slot</h3><form method="post" action="{{ route('configuration.slots.store',$t) }}">@csrf<div class="grid"><div class="col-2 field"><label>Stage</label><select name="stage"><option>BEFORE</option><option>DURING</option><option>AFTER</option><option>REWORK_BEFORE</option><option>REWORK_AFTER</option></select></div><div class="col-2 field"><label>Code</label><input name="slot_code" required></div><div class="col-4 field"><label>Label</label><input name="label" required></div><div class="col-3 field"><label>Close-up hint</label><input name="closeup_hint"></div><div class="col-1 field"><label>Order</label><input type="number" name="sort_order" value="0"></div><div class="col-4"><label><input style="width:auto" type="checkbox" name="mandatory" value="1" checked> Mandatory</label></div><div class="col-4"><label><input style="width:auto" type="checkbox" name="camera_only" value="1" checked> Camera only</label></div><div class="col-4"><label><input style="width:auto" type="checkbox" name="location_required" value="1" checked> Location</label></div></div><button class="btn secondary">Add slot</button></form>
</div>
@endforeach
<div class="card"><h2>Pricing rules</h2><table><thead><tr><th>Package</th><th>Zone</th><th>Amount</th><th>Effective</th></tr></thead><tbody>@foreach($pricing as $p)<tr><td>{{ $p->package_code }}</td><td>{{ $p->zone?->code ?? 'All' }}</td><td>{{ $p->currency }} {{ $p->amount }}</td><td>{{ optional($p->effective_from)->format('d M Y') }} — {{ optional($p->effective_to)->format('d M Y') }}</td></tr>@endforeach</tbody></table></div>
<div class="card"><h2>Reason selectors</h2><table><thead><tr><th>Category</th><th>Code</th><th>Label</th><th>Target</th><th>Payment</th></tr></thead><tbody>@foreach($reasons as $r)<tr><td>{{ $r->category }}</td><td>{{ $r->code }}</td><td>{{ $r->label }}</td><td>{{ $r->target_status }}</td><td>{{ $r->payment_effect }}</td></tr>@endforeach</tbody></table></div>
@endsection
