@extends('layouts.app')
@section('title',$plugin->name)
@section('content')
<div class="page-head"><div><p class="eyebrow">Super Admin · Plugin</p><h1>{{ $plugin->name }}</h1><p class="muted">{{ $plugin->description ?: 'No description supplied.' }}</p></div><div class="stack"><a class="btn secondary" href="{{ route('plugins.index') }}">← Plugins</a>@if(count($plugin->settings_schema??[]))<a class="btn secondary" href="{{ route('plugins.settings',$plugin) }}">Settings</a>@endif</div></div>
<div class="metric-grid"><div class="metric-card"><span>Status</span><strong>{{ $plugin->enabled?'Enabled':'Disabled' }}</strong><small>{{ $plugin->activated_at?->format('d M Y H:i') ?: 'Not activated' }}</small></div><div class="metric-card"><span>Version</span><strong>{{ $plugin->version }}</strong><small>@if($plugin->previous_version)from {{ $plugin->previous_version }}@else fresh install @endif</small></div><div class="metric-card"><span>Compatibility</span><strong>{{ ($health['compatible']??false)?'OK':'Check' }}</strong><small>{{ $health['compatibility_error']??'Core/PHP requirements satisfied' }}</small></div><div class="metric-card"><span>Dependencies</span><strong>{{ ($health['dependencies']??false)?'OK':'Missing' }}</strong><small>{{ $health['dependency_error']??'Dependencies satisfied' }}</small></div></div>
@if($plugin->last_error)<div class="alert error"><strong>Last runtime error:</strong> {{ $plugin->last_error }}</div>@endif
<div class="grid"><div class="col-6 card"><h2>Lifecycle controls</h2><div class="stack">@if($plugin->enabled)<form method="post" action="{{ route('plugins.disable',$plugin) }}">@csrf<button class="btn danger">Disable plugin</button></form>@else<form method="post" action="{{ route('plugins.enable',$plugin) }}">@csrf<button class="btn">Enable plugin</button></form>@endif<form method="post" action="{{ route('plugins.migrate',$plugin) }}">@csrf<button class="btn secondary">Run plugin migrations</button></form></div><hr><p><strong>Author:</strong> {{ $plugin->author ?: '—' }}</p><p><strong>Homepage:</strong> {{ $plugin->homepage ?: '—' }}</p><p><strong>Checksum:</strong><br><code>{{ $plugin->checksum }}</code></p></div>
<div class="col-6 card"><h2>Registered capabilities</h2><p class="muted">Plugins can define permissions for their own features. Plugin manager itself remains Super Admin-only.</p>@forelse($plugin->registered_permissions??[] as $perm)<div class="badge">{{ $perm }}</div>@empty<p>No plugin-specific permissions registered.</p>@endforelse<h3>Requirements</h3><pre>{{ json_encode($plugin->manifest['requires']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre></div></div>
<div class="card"><div class="card-head"><div><h2>Recent plugin activity</h2><p class="muted">Install, update, enable/disable and settings changes are audited separately.</p></div></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Message</th></tr></thead><tbody>@forelse($plugin->activity()->with('actor')->limit(30)->get() as $log)<tr><td>{{ $log->created_at?->format('d M Y H:i:s') }}</td><td>{{ $log->action }}</td><td>{{ $log->actor?->name ?? 'System' }}</td><td>{{ $log->message }}</td></tr>@empty<tr><td colspan="4">No activity yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><h2>Remove plugin</h2><p class="muted">Removing files does not automatically erase plugin-owned business data. Tick purge only when you deliberately want the plugin uninstall callback to remove its own data.</p><form method="post" action="{{ route('plugins.delete',$plugin) }}" onsubmit="return confirm('Remove this plugin?')">@csrf @method('DELETE')<label><input type="checkbox" name="purge_data" value="1"> Allow plugin uninstall callback to purge its own data</label><br><br><button class="btn danger">Remove plugin</button></form></div>
@endsection
