@extends('layouts.app')
@section('title','System Settings')
@section('content')
<div class="page-head"><div><p class="eyebrow">Super Admin</p><h1>System settings</h1><p class="muted">Branding, registration, OTP, evidence retention, SMTP and default permission policy.</p></div></div>
<form method="post" action="{{ route('settings.update') }}" enctype="multipart/form-data">@csrf
<div class="card"><div class="card-head"><div><h2>Brand & design system</h2><p class="muted">Applies consistently across mobile PWA and desktop layouts.</p></div></div><div class="grid">
<div class="col-4 field"><label>Brand name</label><input name="app_brand_name" value="{{ old('app_brand_name',$settings['app_brand_name']->value ?? 'Scratchgard') }}" required></div>
<div class="col-8 field"><label>Footer text</label><input name="footer_text" value="{{ old('footer_text',$settings['footer_text']->value ?? 'Scratchgard PPF Operations') }}"></div>
<div class="col-3 field"><label>Logo</label><input type="file" name="logo" accept="image/*"></div><div class="col-3 field"><label>Favicon</label><input type="file" name="favicon" accept="image/*"></div>
<div class="col-2 field"><label>Site colour</label><input type="color" name="theme_color" value="{{ old('theme_color',$settings['theme_color']->value ?? '#0B1727') }}"></div><div class="col-2 field"><label>Accent</label><input type="color" name="accent_color" value="{{ old('accent_color',$settings['accent_color']->value ?? '#27B7E8') }}"></div><div class="col-2 field"><label>Text</label><input type="color" name="text_color" value="{{ old('text_color',$settings['text_color']->value ?? '#EDF7FF') }}"></div>
<div class="col-6 field"><label>Font stack</label><input name="font_family" value="{{ old('font_family',$settings['font_family']->value ?? 'Inter, ui-sans-serif, system-ui, sans-serif') }}"></div><div class="col-3 field"><label>Base font size</label><input type="number" name="base_font_size" value="{{ old('base_font_size',$settings['base_font_size']->value ?? 16) }}"></div><div class="col-3 field"><label>Heading scale</label><input type="number" step="0.01" name="heading_scale" value="{{ old('heading_scale',$settings['heading_scale']->value ?? 1.22) }}"></div>
</div></div>

<div class="card"><h2>Registration & unique identity verification</h2><div class="grid">
<div class="col-4 field"><label>Required identity</label><select name="registration_identity_mode">@foreach(['email_or_mobile'=>'Email OR mobile','email_only'=>'Email only','mobile_only'=>'Mobile only','both'=>'Email AND mobile'] as $k=>$l)<option value="{{ $k }}" @selected(($settings['registration_identity_mode']->value ?? 'email_or_mobile')===$k)>{{ $l }}</option>@endforeach</select></div>
<div class="col-4 field"><label>Zone selection during registration</label><select name="registration_zone_selection_mode">@foreach(['hidden_auto'=>'Auto assign best matching zone','show_single'=>'Show matching zones; user selects one','show_multi'=>'Show matching zones; user may select multiple when global multi-zone is enabled'] as $k=>$l)<option value="{{ $k }}" @selected(($settings['registration_zone_selection_mode']->value ?? 'hidden_auto')===$k)>{{ $l }}</option>@endforeach</select></div>
<div class="col-2 field"><label>Default country code</label><input name="default_mobile_country_code" value="{{ old('default_mobile_country_code',$settings['default_mobile_country_code']->value ?? '+91') }}" maxlength="5"><small class="muted">Mobile is always 10 national digits after this code.</small></div><div class="col-2 field"><label>OTP expiry minutes</label><input type="number" name="otp_expiry_minutes" value="{{ old('otp_expiry_minutes',$settings['otp_expiry_minutes']->value ?? 10) }}"></div>
<div class="col-2 field"><label>Mobile OTP driver</label><select name="mobile_otp_driver"><option value="log" @selected(($settings['mobile_otp_driver']->value ?? 'log')==='log')>Log (setup only)</option><option value="generic_http" @selected(($settings['mobile_otp_driver']->value ?? '')==='generic_http')>Generic HTTP SMS</option></select></div>
<div class="col-8 field"><label>Generic SMS endpoint</label><input name="mobile_otp_http_url" value="{{ old('mobile_otp_http_url',$settings['mobile_otp_http_url']->value ?? '') }}" placeholder="https://sms-provider.example/send"></div><div class="col-4 field"><label>Bearer token</label><input type="password" name="mobile_otp_http_token" placeholder="Leave blank to keep existing"></div>
<div class="col-6"><label class="check"><input type="checkbox" name="registration_require_existing_zone" value="1" @checked(($settings['registration_require_existing_zone']->value ?? '1')==='1')> Reject registration when PIN has no active Scratchgard zone</label></div>
<div class="col-6"><label class="check"><input type="checkbox" name="allow_multiple_zones_default" value="1" @checked(($settings['allow_multiple_zones_default']->value ?? '0')==='1')> Allow multiple zones by default (OFF recommended)</label></div>
<div class="col-6"><label class="check"><input type="checkbox" name="user_self_zone_change" value="1" @checked(($settings['user_self_zone_change']->value ?? '1')==='1')> Allow profile PIN update to re-resolve/change user's primary zone</label></div>
</div><div class="alert warning">Recommended production policy: one primary zone per Applicator/Zonal Manager. Enable multi-zone only globally when truly required, or per-user from the user editor.</div></div>

<div class="card"><h2>Operational controls</h2><div class="grid"><div class="col-4 field"><label>Payment tracking mode</label><select name="payment_tracking_mode"><option value="approval_status" @selected(($settings['payment_tracking_mode']->value ?? 'approval_status')==='approval_status')>Approved work = Payment Done (current)</option><option value="manual_finance" @selected(($settings['payment_tracking_mode']->value ?? 'approval_status')==='manual_finance')>Manual finance payment recording</option></select><small class="muted">In status-based mode, approval creates a paid/done ledger entry. Later rework never silently reverses it.</small></div><div class="col-3 field"><label>Evidence retention days</label><input type="number" name="evidence_retention_days" value="{{ old('evidence_retention_days',$settings['evidence_retention_days']->value ?? 365) }}"></div><div class="col-3 field"><label>Default geofence metres</label><input type="number" name="default_geofence_radius_m" value="{{ old('default_geofence_radius_m',$settings['default_geofence_radius_m']->value ?? 250) }}"></div><div class="col-6"><label class="check"><input type="checkbox" name="allow_zonal_manager_approval" value="1" @checked(($settings['allow_zonal_manager_approval']->value ?? '0')==='1')> Allow Zonal Managers to approve completed work</label><label class="check"><input type="checkbox" name="allow_zonal_manager_kyc_approval" value="1" @checked(($settings['allow_zonal_manager_kyc_approval']->value ?? '0')==='1')> Allow Zonal Managers to approve KYC</label></div></div></div>

<div class="card"><h2>Email notification policy</h2><p class="muted">Operational emails are sent to the people directly assigned to a work/ticket plus enabled oversight roles. Failures are logged so SMTP problems do not silently disappear.</p><div class="grid"><div class="col-4"><label class="check"><input type="checkbox" name="email_notifications_enabled" value="1" @checked(($settings['email_notifications_enabled']->value ?? '1')==='1')> Send event emails</label></div><div class="col-4"><label class="check"><input type="checkbox" name="email_notify_super_admins" value="1" @checked(($settings['email_notify_super_admins']->value ?? '1')==='1')> Include active Super Admins</label></div><div class="col-4"><label class="check"><input type="checkbox" name="email_notify_work_delegators" value="1" @checked(($settings['email_notify_work_delegators']->value ?? '1')==='1')> Include active Work Delegators on work events</label></div></div></div>
<div class="card"><h2>SMTP email</h2><div class="grid"><div class="col-5 field"><label>SMTP host</label><input name="smtp_host" value="{{ old('smtp_host',$settings['smtp_host']->value ?? '') }}"></div><div class="col-2 field"><label>Port</label><input type="number" name="smtp_port" value="{{ old('smtp_port',$settings['smtp_port']->value ?? 587) }}"></div><div class="col-5 field"><label>Username</label><input name="smtp_username" value="{{ old('smtp_username',$settings['smtp_username']->value ?? '') }}"></div><div class="col-6 field"><label>Password</label><input type="password" name="smtp_password" placeholder="Leave blank to keep current"></div><div class="col-3 field"><label>From email</label><input type="email" name="smtp_from_address" value="{{ old('smtp_from_address',$settings['smtp_from_address']->value ?? '') }}"></div><div class="col-3 field"><label>From name</label><input name="smtp_from_name" value="{{ old('smtp_from_name',$settings['smtp_from_name']->value ?? 'Scratchgard') }}"></div></div></div>
<button class="btn good wide">Save all settings</button></form>
<div class="card"><h2>Test SMTP</h2><form method="post" action="{{ route('settings.test-mail') }}" class="stack">@csrf<input style="max-width:420px" type="email" name="test_email" placeholder="you@example.com" required><button class="btn secondary">Send test email</button></form></div>

<div class="card"><h2>Recent email delivery log</h2><p class="muted">Last 30 transactional email attempts. Failed sends help diagnose SMTP/cPanel configuration without losing the underlying workflow event.</p><div class="table-wrap"><table><thead><tr><th>Time</th><th>Event</th><th>Email</th><th>Subject</th><th>Status</th></tr></thead><tbody>@forelse($notificationLogs as $n)<tr><td>{{ $n->created_at?->format('d M H:i') }}</td><td>{{ $n->event_type }}</td><td>{{ $n->email }}</td><td>{{ $n->subject }}</td><td><span class="badge">{{ $n->status }}</span>@if($n->error)<br><small class="text-danger">{{ \Illuminate\Support\Str::limit($n->error,120) }}</small>@endif</td></tr>@empty<tr><td colspan="5" class="muted">No notification attempts yet.</td></tr>@endforelse</tbody></table></div></div>
@endsection
